### ISSUE TITLE
Backup failed because The dump process failed with exitcode 2

### ISSUE THREAD

**Issue by PooX** [spatie/laravel-backup#1035]
Hello, there is my error:

```
root@mail:/var/www/prijevodi-titlovi.org# php artisan backup:run
Starting backup...
Dumping database smf...
Backup failed because The dump process failed with exitcode 2 : Misuse of shell                                                                                                     builtins : mysqldump: Got error: 1698: "Access denied for user 'root'@'localhost                                                                                                    '" when trying to connect
.
#0 /var/www/prijevodi-titlovi.org/vendor/spatie/db-dumper/src/DbDumper.php(246):                                                                                                     Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully(Object(Symf                                                                                                    ony\Component\Process\Process))
#1 /var/www/prijevodi-titlovi.org/vendor/spatie/db-dumper/src/Databases/MySql.ph                                                                                                    p(190): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul(Object(Symfony\Compon                                                                                                    ent\Process\Process), '/var/www/prijev...')
#2 /var/www/prijevodi-titlovi.org/vendor/spatie/laravel-backup/src/Tasks/Backup/                                                                                                    BackupJob.php(250): Spatie\DbDumper\Databases\MySql->dumpToFile('/var/www/prijev                                                                                                    ...')
#3 [internal function]: Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Task                                                                                                    s\Backup\{closure}(Object(Spatie\DbDumper\Databases\MySql), 'mysql')
#4 /var/www/prijevodi-titlovi.org/vendor/laravel/framework/src/Illuminate/Suppor                                                                                                    t/Collection.php(638): array_map(Object(Closure), Array, Array)
#5 /var/www/prijevodi-titlovi.org/vendor/spatie/laravel-backup/src/Tasks/Backup/                                                                                                    BackupJob.php(253): Illuminate\Support\Collection->map(Object(Closure))
#6 /var/www/prijevodi-titlovi.org/vendor/spatie/laravel-backup/src/Tasks/Backup/                                                                                                    BackupJob.php(167): Spatie\Backup\Tasks\Backup\BackupJob->dumpDatabases()
#7 /var/www/prijevodi-titlovi.org/vendor/spatie/laravel-backup/src/Tasks/Backup/                                                                                                    BackupJob.php(143): Spatie\Backup\Tasks\Backup\BackupJob->createBackupManifest()
#8 /var/www/prijevodi-titlovi.org/vendor/spatie/laravel-backup/src/Commands/Back                                                                                                    upCommand.php(52): Spatie\Backup\Tasks\Backup\BackupJob->run()
#9 [internal function]: Spatie\Backup\Commands\BackupCommand->handle()
#10 /var/www/prijevodi-titlovi.org/vendor/laravel/framework/src/Illuminate/Conta                                                                                                    iner/BoundMethod.php(32): call_user_func_array(Array, Array)
#11 /var/www/prijevodi-titlovi.org/vendor/laravel/framework/src/Illuminate/Conta                                                                                                    iner/Util.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closu                                                                                                    re}()
#12 /var/www/prijevodi-titlovi.org/vendor/laravel/framework/src/Illuminate/Conta                                                                                                    iner/BoundMethod.php(90): Illuminate\Container\Util::unwrapIfClosure(Object(Clos                                                                                                    ure))
#13 /var/www/prijevodi-titlovi.org/vendor/laravel/framework/src/Illuminate/Conta                                                                                                    iner/BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod(Obje                                                                                                    ct(Illuminate\Foundation\Application), Array, Object(Closure))
#14 /var/www/prijevodi-titlovi.org/vendor/laravel/framework/src/Illuminate/Conta                                                                                                    iner/Container.php(590): Illuminate\Container\BoundMethod::call(Object(Illuminat                                                                                                    e\Foundation\Application), Array, Array, NULL)
#15 /var/www/prijevodi-titlovi.org/vendor/laravel/framework/src/Illuminate/Conso                                                                                                    le/Command.php(201): Illuminate\Container\Container->call(Array)
#16 /var/www/prijevodi-titlovi.org/vendor/symfony/console/Command/Command.php(25                                                                                                    5): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\A                                                                                                    rgvInput), Object(Illuminate\Console\OutputStyle))
#17 /var/www/prijevodi-titlovi.org/vendor/laravel/framework/src/Illuminate/Conso                                                                                                    le/Command.php(188): Symfony\Component\Console\Command\Command->run(Object(Symfo                                                                                                    ny\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#18 /var/www/prijevodi-titlovi.org/vendor/spatie/laravel-backup/src/Commands/Bas                                                                                                    eCommand.php(16): Illuminate\Console\Command->run(Object(Symfony\Component\Conso                                                                                                    le\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/prijevodi-titlovi.org/vendor/symfony/console/Application.php(1012):                                                                                                     Spatie\Backup\Commands\BaseCommand->run(Object(Symfony\Component\Console\Input\                                                                                                    ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/prijevodi-titlovi.org/vendor/symfony/console/Application.php(272):                                                                                                     Symfony\Component\Console\Application->doRunCommand(Object(Spatie\Backup\Command                                                                                                    s\BackupCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symf                                                                                                    ony\Component\Console\Output\ConsoleOutput))
#21 /var/www/prijevodi-titlovi.org/vendor/symfony/console/Application.php(148):                                                                                                     Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\In                                                                                                    put\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/prijevodi-titlovi.org/vendor/laravel/framework/src/Illuminate/Conso                                                                                                    le/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfon                                                                                                    y\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\Co                                                                                                    nsoleOutput))
#23 /var/www/prijevodi-titlovi.org/vendor/laravel/framework/src/Illuminate/Found                                                                                                    ation/Console/Kernel.php(131): Illuminate\Console\Application->run(Object(Symfon                                                                                                    y\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\Co                                                                                                    nsoleOutput))
#24 /var/www/prijevodi-titlovi.org/artisan(37): Illuminate\Foundation\Console\Ke                                                                                                    rnel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\C                                                                                                    omponent\Console\Output\ConsoleOutput))
#25 {main}
Backup failed because: The dump process failed with exitcode 2 : Misuse of shell                                                                                                     builtins : mysqldump: Got error: 1698: "Access denied for user 'root'@'localhos                                                                                                    t'" when trying to connect

```

But in my database.php settings file it is:

```
 'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'smf'),
            'username' => env('DB_USERNAME', 'backup'),
            'password' => env('DB_PASSWORD', 'bckppassword'),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => false,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
            'dump' => [
                'dump_binary_path' => '/usr/bin/', // only the path, so without `mysqldump` or `pg_dump`
                'use_single_transaction',
                'timeout' => 60 * 5, // 5 minute timeout
            ]
        ],
```

So i don't undestead why it need to connect throw root user or what is problem. Also i cleared config cache, so everything is updated.

Also, when i change it to root it only work on my local host becouse i dont need password, but when i change to some user that have all granted and all allows, it won't run backup.

**Comment by ncatanchin** [comment]
Check if you have a `.my.cnf` setup somewhere, for me it was in my home directory.

This package creates a temporary credentials configuration file, and with `mysqldump` runs something like:

`mysqldump --defaults-extra-file="/tmp/phpCdasdf"`

For me, this _failed_ to override what I had setup in `.my.cnf`. As soon as I disabled this file - simply renamed temporarily, the dump worked.

Note I also tested with:

`mysqldump --defaults-file="..."`

This _did_ override my local `.my.cnf`.

**Comment by PooX** [comment]
I found it in root folder:

`# NOTE: This file is used by several programs:
#   - daily SQL backup script: /var/vmail/backup/backup_mysql.sh
#   - iRedAPD upgrade script
#   - iRedAdmin upgrade script
[client]
user=root
password="SOME CUSTOM PASSWORD I NOWHERE USE"
`

So that i change there data for my backup user?

**Comment by ncatanchin** [comment]
Try to rename this file, which will disable it - then run your backup. You may find that it works - this is the reason it is trying to login to your application database with the `root` user.

From there, I'm not sure what the definitive solution would be for your configuration.

I see this as a limitation / shortcoming in the package, but I may be wrong. You should be able to have a `.my.cnf` configured, without it conflicting with the backup process. I'm not sure of the reason for using `--defaults-extra-file` instead of `--defaults-file` - but imagine this would cause problems for people who _do_ want the `.my.cnf` to override / supplement the backup configuration!

**Comment by PooX** [comment]
Wow, that's actually worked. Thank you. ;D
