### ISSUE TITLE
Backup failed because: fwrite(): write of some bytes failed with errno=28 No space left on device.

### ISSUE THREAD

**Issue by umarfarooqumzen** [spatie/laravel-backup#1123]
This is the output after I run the corn job from a shared hosting. everything works fine on my local. Can you please look into it and provide more info. I have enough space on my disk so why is this happening?
```
Starting backup...
Dumping database mydatabase-313037b0b2...
Backup failed because fwrite(): write of 117 bytes failed with errno=28 No space left on device.
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'fwrite(): write...', '/home/sites/12a...', 194, Array)
#1 /home/sites/12a/1/11c10cdfd2/vendor/spatie/db-dumper/src/Databases/MySql.php(194): fwrite(Resource id #713, '[client]\nuser =...')
#2 /home/sites/12a/1/11c10cdfd2/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(253): Spatie\DbDumper\Databases\MySql->dumpToFile('/home/sites/12a...')
#3 [internal function]: Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup\{closure}(Object(Spatie\DbDumper\Databases\MySql), 'mysql')
#4 /home/sites/12a/1/11c10cdfd2/vendor/laravel/framework/src/Illuminate/Support/Collection.php(638): array_map(Object(Closure), Array, Array)
#5 /home/sites/12a/1/11c10cdfd2/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(256): Illuminate\Support\Collection->map(Object(Closure))
#6 /home/sites/12a/1/11c10cdfd2/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(170): Spatie\Backup\Tasks\Backup\BackupJob->dumpDatabases()
#7 /home/sites/12a/1/11c10cdfd2/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(146): Spatie\Backup\Tasks\Backup\BackupJob->createBackupManifest()
#8 /home/sites/12a/1/11c10cdfd2/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(56): Spatie\Backup\Tasks\Backup\BackupJob->run()
#9 [internal function]: Spatie\Backup\Commands\BackupCommand->handle()
#10 /home/sites/12a/1/11c10cdfd2/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): call_user_func_array(Array, Array)
#11 /home/sites/12a/1/11c10cdfd2/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#12 /home/sites/12a/1/11c10cdfd2/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#13 /home/sites/12a/1/11c10cdfd2/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(39): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#14 /home/sites/12a/1/11c10cdfd2/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#15 /home/sites/12a/1/11c10cdfd2/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call(Array)
#16 /home/sites/12a/1/11c10cdfd2/vendor/symfony/console/Command/Command.php(258): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#17 /home/sites/12a/1/11c10cdfd2/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#18 /home/sites/12a/1/11c10cdfd2/vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(16): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /home/sites/12a/1/11c10cdfd2/vendor/symfony/console/Application.php(916): Spatie\Backup\Commands\BaseCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /home/sites/12a/1/11c10cdfd2/vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand(Object(Spatie\Backup\Commands\BackupCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /home/sites/12a/1/11c10cdfd2/vendor/symfony/console/Application.php(140): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /home/sites/12a/1/11c10cdfd2/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /home/sites/12a/1/11c10cdfd2/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /home/sites/12a/1/11c10cdfd2/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 {main}
Sending notification failed
Backup failed because: fwrite(): write of 117 bytes failed with errno=28 No space left on device.

In AbstractSmtpTransport.php line 445:
                                                        
  Expected response code 250 but got an empty response  
                                                        
```

**Comment by zOxta** [comment]
@umarfarooqumzen Most likely your shared hosting does not allow you to write data in the temp directory. Locally, it works because you can do that. I would not say this is an issue with the package.

**Comment by umarfarooqumzen** [comment]
I'll be honest, I had this package setup for a week now I have two schedule one for clean up and one for backup at night and the time difference between both jobs is 30 mins so someday it does the cleanup only and someday it does both so I am a little confused where is the problem it's not even triggering the email error I was receiving back then. I deleted the backup folder and changed permission so it works now near to perfection but still doesn't work sometimes

**Comment by umarfarooqumzen** [comment]
@zOxta my hosting is shared but provides me with SSH access and alot of rights a typical shared hosting doesn't provide. It does work but it's just that sometimes the cron job doesn't send me the email weird
