### ISSUE TITLE
Spatie\DbDumper\Databases\MySql::setTempFileHandle(): Return value must be of type mixed, none returned

### ISSUE THREAD

**Issue by nhtahoe** [spatie/laravel-backup#1277]
Fresh install of laravel backup on PHP 8.0.3, Laravel 8.35.1, When I run `php artisan backup:run` I get the following exception:
```
[2021-04-01 04:25:34] local.ERROR: Spatie\DbDumper\Databases\MySql::setTempFileHandle(): Return value must be of type mixed, none returned {"exception":"[object] (TypeError(code: 0): Spatie\\DbDumper\\Databases\\MySql::setTempFileHandle(): Return value must be of type mixed, none returned at /home/forge/example.com/vendor/spatie/db-dumper/src/Databases/MySql.php:296)
[stacktrace]
#0 /home/forge/example.com/vendor/spatie/db-dumper/src/Databases/MySql.php(137): Spatie\\DbDumper\\Databases\\MySql->setTempFileHandle()
#1 /home/forge/example.com/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(244): Spatie\\DbDumper\\Databases\\MySql->dumpToFile()
#2 [internal function]: Spatie\\Backup\\Tasks\\Backup\\BackupJob->Spatie\\Backup\\Tasks\\Backup\\{closure}()
#3 /home/forge/example.com/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(640): array_map()
#4 /home/forge/example.com/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(247): Illuminate\\Support\\Collection->map()
#5 /home/forge/example.com/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(164): Spatie\\Backup\\Tasks\\Backup\\BackupJob->dumpDatabases()
#6 /home/forge/example.com/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(140): Spatie\\Backup\\Tasks\\Backup\\BackupJob->createBackupManifest()
#7 /home/forge/example.com/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(54): Spatie\\Backup\\Tasks\\Backup\\BackupJob->run()
#8 /home/forge/example.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Spatie\\Backup\\Commands\\BackupCommand->handle()
#9 /home/forge/example.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /home/forge/example.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#11 /home/forge/example.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#12 /home/forge/example.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(611): Illuminate\\Container\\BoundMethod::call()
#13 /home/forge/example.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#14 /home/forge/example.com/vendor/symfony/console/Command/Command.php(256): Illuminate\\Console\\Command->execute()
#15 /home/forge/example.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#16 /home/forge/example.com/vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(16): Illuminate\\Console\\Command->run()
#17 /home/forge/example.com/vendor/symfony/console/Application.php(971): Spatie\\Backup\\Commands\\BaseCommand->run()
#18 /home/forge/example.com/vendor/symfony/console/Application.php(290): Symfony\\Component\\Console\\Application->doRunCommand()
#19 /home/forge/example.com/vendor/symfony/console/Application.php(166): Symfony\\Component\\Console\\Application->doRun()
#20 /home/forge/example.com/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\\Component\\Console\\Application->run()
#21 /home/forge/example.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#22 /home/forge/example.com/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#23 {main}
"} 
```

In Spatie\DbDumper\Databases\MySql If I remove the `: mixed` from `public function setTempFileHandle($temfFileHandle)` the error goes away and the backup runs fine.

**Comment by freekmurze** [comment]
Thanks for the PR on db-dumper. It has been merged and released.
