### ISSUE TITLE
Backup Success Notification Failing to Send

### ISSUE THREAD

**Issue by jbeales** [spatie/laravel-backup#1417]
I think there may be some sort of problem where residual data from a `backup:clean` run infects a subsequent `backup:run` and causes the Backup Successful notification to fail.

Sometimes the Backup Successful notification fails. Looking at the log from last night, when it failed, it appears that it is trying to get the Size of the wrong file in the BackupWasSuccessful notification, but why would it look for the wrong file name.

Here is last night's console output from `backup:run`:
```
Starting backup...
Dumping database 4roadservice...
Determining files to backup...
Zipping 30092 files and directories...
Created zip containing 30092 files and directories. Size is 2.48 GB
Copying zip to disk named backup...
Successfully copied zip to disk named backup.
Sending notification failed
Backup completed!
```

The backup file, `4RoadService.com/2021-10-15-02-45-02.zip` exists in the final destination.

Here is the error from the error log when sending the notification failed, with the backtrace:
```
[2021-10-15 03:23:10] production.ERROR: File not found at path: 4RoadService.com/2021-07-10-02-45-01.zip {"route":null,"exception":"[object] (League\\Flysystem\\FileNotFoundException(code: 0): File not found at path: 4RoadService.com/2021-07-10-02-45-01.zip at /mnt/data/www/4RoadService/releases/20211010165700/vendor/league/flysystem/src/Filesystem.php:390)
[stacktrace]
#0 /mnt/data/www/4RoadService/releases/20211010165700/vendor/league/flysystem/src/Filesystem.php(329): League\\Flysystem\\Filesystem->assertPresent()
#1 /mnt/data/www/4RoadService/releases/20211010165700/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(412): League\\Flysystem\\Filesystem->getSize()
#2 /mnt/data/www/4RoadService/releases/20211010165700/vendor/spatie/laravel-backup/src/BackupDestination/Backup.php(79): Illuminate\\Filesystem\\FilesystemAdapter->size()
#3 /mnt/data/www/4RoadService/releases/20211010165700/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(60): Spatie\\Backup\\BackupDestination\\Backup->size()
#4 /mnt/data/www/4RoadService/releases/20211010165700/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(452): Illuminate\\Support\\HigherOrderCollectionProxy->Illuminate\\Support\\{closure}()
#5 /mnt/data/www/4RoadService/releases/20211010165700/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(741): Illuminate\\Support\\Collection->Illuminate\\Support\\Traits\\{closure}()
#6 /mnt/data/www/4RoadService/releases/20211010165700/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(453): Illuminate\\Support\\Collection->reduce()
#7 /mnt/data/www/4RoadService/releases/20211010165700/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(61): Illuminate\\Support\\Collection->sum()
#8 /mnt/data/www/4RoadService/releases/20211010165700/vendor/spatie/laravel-backup/src/BackupDestination/BackupCollection.php(47): Illuminate\\Support\\HigherOrderCollectionProxy->__call()
#9 /mnt/data/www/4RoadService/releases/20211010165700/vendor/spatie/laravel-backup/src/Notifications/BaseNotification.php(53): Spatie\\Backup\\BackupDestination\\BackupCollection->size()
#10 /mnt/data/www/4RoadService/releases/20211010165700/vendor/spatie/laravel-backup/src/Notifications/Notifications/BackupWasSuccessful.php(28): Spatie\\Backup\\Notifications\\BaseNotification->backupDestinationProperties()
#11 /mnt/data/www/4RoadService/releases/20211010165700/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(51): Spatie\\Backup\\Notifications\\Notifications\\BackupWasSuccessful->toMail()
#12 /mnt/data/www/4RoadService/releases/20211010165700/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(148): Illuminate\\Notifications\\Channels\\MailChannel->send()
#13 /mnt/data/www/4RoadService/releases/20211010165700/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(106): Illuminate\\Notifications\\NotificationSender->sendToNotifiable()
#14 /mnt/data/www/4RoadService/releases/20211010165700/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\\Notifications\\NotificationSender->Illuminate\\Notifications\\{closure}()
#15 /mnt/data/www/4RoadService/releases/20211010165700/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(109): Illuminate\\Notifications\\NotificationSender->withLocale()
#16 /mnt/data/www/4RoadService/releases/20211010165700/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(79): Illuminate\\Notifications\\NotificationSender->sendNow()
#17 /mnt/data/www/4RoadService/releases/20211010165700/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(39): Illuminate\\Notifications\\NotificationSender->send()
#18 /mnt/data/www/4RoadService/releases/20211010165700/vendor/laravel/framework/src/Illuminate/Notifications/RoutesNotifications.php(18): Illuminate\\Notifications\\ChannelManager->send()
#19 /mnt/data/www/4RoadService/releases/20211010165700/vendor/spatie/laravel-backup/src/Notifications/EventHandler.php(33): Spatie\\Backup\\Notifications\\Notifiable->notify()
#20 /mnt/data/www/4RoadService/releases/20211010165700/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(404): Spatie\\Backup\\Notifications\\EventHandler->Spatie\\Backup\\Notifications\\{closure}()
#21 /mnt/data/www/4RoadService/releases/20211010165700/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#22 /mnt/data/www/4RoadService/releases/20211010165700/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(450): Illuminate\\Events\\Dispatcher->dispatch()
#23 /mnt/data/www/4RoadService/releases/20211010165700/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(289): event()
#24 /mnt/data/www/4RoadService/releases/20211010165700/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(656): Spatie\\Backup\\Tasks\\Backup\\BackupJob->Spatie\\Backup\\Tasks\\Backup\\{closure}()
#25 /mnt/data/www/4RoadService/releases/20211010165700/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(292): rescue()
#26 /mnt/data/www/4RoadService/releases/20211010165700/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(276): Spatie\\Backup\\Tasks\\Backup\\BackupJob->sendNotification()
#27 /mnt/data/www/4RoadService/releases/20211010165700/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(234): Spatie\\Backup\\Tasks\\Backup\\BackupJob->Spatie\\Backup\\Tasks\\Backup\\{closure}()
#28 /mnt/data/www/4RoadService/releases/20211010165700/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(282): Illuminate\\Support\\Collection->each()
#29 /mnt/data/www/4RoadService/releases/20211010165700/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(155): Spatie\\Backup\\Tasks\\Backup\\BackupJob->copyToBackupDestinations()
#30 /mnt/data/www/4RoadService/releases/20211010165700/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(56): Spatie\\Backup\\Tasks\\Backup\\BackupJob->run()
#31 /mnt/data/www/4RoadService/releases/20211010165700/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Spatie\\Backup\\Commands\\BackupCommand->handle()
#32 /mnt/data/www/4RoadService/releases/20211010165700/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#33 /mnt/data/www/4RoadService/releases/20211010165700/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#34 /mnt/data/www/4RoadService/releases/20211010165700/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#35 /mnt/data/www/4RoadService/releases/20211010165700/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#36 /mnt/data/www/4RoadService/releases/20211010165700/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#37 /mnt/data/www/4RoadService/releases/20211010165700/vendor/symfony/console/Command/Command.php(299): Illuminate\\Console\\Command->execute()
#38 /mnt/data/www/4RoadService/releases/20211010165700/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#39 /mnt/data/www/4RoadService/releases/20211010165700/vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(16): Illuminate\\Console\\Command->run()
#40 /mnt/data/www/4RoadService/releases/20211010165700/vendor/symfony/console/Application.php(978): Spatie\\Backup\\Commands\\BaseCommand->run()
#41 /mnt/data/www/4RoadService/releases/20211010165700/vendor/symfony/console/Application.php(295): Symfony\\Component\\Console\\Application->doRunCommand()
#42 /mnt/data/www/4RoadService/releases/20211010165700/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun()
#43 /mnt/data/www/4RoadService/releases/20211010165700/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\\Component\\Console\\Application->run()
#44 /mnt/data/www/4RoadService/releases/20211010165700/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#45 /mnt/data/www/4RoadService/releases/20211010165700/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#46 {main}
"} 
```

The notification tried to get the size of `4RoadService.com/2021-07-10-02-45-01.zip` - a date in July - not  `4RoadService.com/2021-10-15-02-45-02.zip` that was just uploaded and created.   `4RoadService.com/2021-07-10-02-45-01.zip` is the name of a backup that laravel-backup tried to clean up last night and failed, because it doesn't exist, (we had some problems with our external backup destination over the summer).

The `backup:clean` command runs an hour and a half before `backup:run`.

Is something cached or memoized in a way that might cause the failed cleanup filename to be used when sending a BackupSuccessful notification?

**Comment by sandrobocon** [comment]
We have been facing something very similar, we aren't using notification, so I am not sure if it is trying or not to send.
But it is throwing an error with an old filename in s3 as well.

Daily it runs:
```
backup:run --only-db=1 --only-to-disk=s3 --filename='production-2021-12-14-T04-00-03-0500.zip'
```
It seems to do everything, like make the backup and send to S3, but it throws an exception to a really old file (every day)
```
League\Flysystem\FileNotFoundException: File not found at path: laravel-backup/production-2021-06-18-T04-39-33-0400.zip
```

It seems to have some kind of cache as @jbeales said, tried to clear with `optimize:clear` but no success so far.

**Comment by freekmurze** [comment]
I haven't come across this error myself. I guess it's caused by some sort of race condition. 

Feel free to send in a PR that fixes it for you.
