### ISSUE TITLE
"Unknown table 'COLUMN_STATISTICS' in information_schema"

### ISSUE THREAD

**Issue by tricki** [spatie/laravel-backup#1541]
I just installed laravel-backup on an existing Laravel app (used with Laravel Sail) and got the following error when running "backup:run":

```
Backup failed because The dump process failed with a none successful exitcode.
Exitcode
========
2: Misuse of shell builtins

Output
======
<no output>

Error Output
============
mysqldump: Couldn't execute 'SELECT COLUMN_NAME,                       JSON_EXTRACT(HISTOGRAM, '$."number-of-buckets-specified"')                FROM information_schema.COLUMN_STATISTICS                WHERE SCHEMA_NAME = 'finnova_facm' AND TABLE_NAME = 'event_registrations';': Unknown table 'COLUMN_STATISTICS' in information_schema (1109)
```

<details><summary>Stacktrace</summary>
<p>

```
#0 /var/www/html/vendor/spatie/db-dumper/src/DbDumper.php(178): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully()
#1 /var/www/html/vendor/spatie/db-dumper/src/Databases/MySql.php(143): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul()
#2 /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(274): Spatie\DbDumper\Databases\MySql->dumpToFile()
#3 [internal function]: Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup\{closure}()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(558): array_map()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(723): Illuminate\Support\Arr::map()
#6 /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(277): Illuminate\Support\Collection->map()
#7 /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(188): Spatie\Backup\Tasks\Backup\BackupJob->dumpDatabases()
#8 /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(160): Spatie\Backup\Tasks\Backup\BackupJob->createBackupManifest()
#9 /var/www/html/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(58): Spatie\Backup\Tasks\Backup\BackupJob->run()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Spatie\Backup\Commands\BackupCommand->handle()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\BoundMethod::call()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call()
#16 /var/www/html/vendor/symfony/console/Command/Command.php(308): Illuminate\Console\Command->execute()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#18 /var/www/html/vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(28): Illuminate\Console\Command->run()
#19 /var/www/html/vendor/symfony/console/Application.php(998): Spatie\Backup\Commands\BaseCommand->run()
#20 /var/www/html/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#21 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\Component\Console\Application->run()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#24 /var/www/html/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#25 {main}
Backup failed because: The dump process failed with a none successful exitcode.
Exitcode
========
2: Misuse of shell builtins

Output
======
<no output>

Error Output
============
mysqldump: Couldn't execute 'SELECT COLUMN_NAME,                       JSON_EXTRACT(HISTOGRAM, '$."number-of-buckets-specified"')                FROM information_schema.COLUMN_STATISTICS                WHERE SCHEMA_NAME = 'finnova_facm' AND TABLE_NAME = 'event_registrations';': Unknown table 'COLUMN_STATISTICS' in information_schema (1109)
.
```

</p>
</details>

**Versions:**

macOS 12.3.1
PHP 8.1.5
Laravel 9.17.0
MariaDB 10.5.8

I found a mention of the column_statics table [in the db-dumper readme](https://github.com/spatie/db-dumper#dont-use-column_statics-table-with-some-old-version-of-mysql-service) but that didn't help or even change the error message.

Here's the command that is run:

```
'mysqldump' --defaults-extra-file="/tmp/phpKpBIR6" --skip-comments --extended-insert --column-statistics=0 --default-character-set=utf8mb4 db_name
```

Happy for any help or pointers.

**Comment by PaolaRuby** [comment]
Use the correct mysqldump

**Comment by tricki** [comment]
Hi, thanks for the response.

I'm not sure which mysqldump is "correct", do you mean a specific version? If I run `mysqldump --version` inside the container the output is:

```
mysqldump  Ver 8.0.29-0ubuntu0.21.10.2 for Linux on aarch64 ((Ubuntu))
```

I actually just solved it by adding `--column-statistics=0` to the connection config as described in [the docs section about increasing timeout](https://spatie.be/docs/laravel-backup/v8/installation-and-setup#content-dumping-the-database). It's hidden by the horizontal overflow and the search doesn't return anything for "--column-statistics", that's why I didn't see it before.
