### ISSUE TITLE
Backup failure with v4

### ISSUE THREAD

**Issue by bridgeport** [spatie/laravel-backup#270]
First, thanks for this great package. I'm having problems with v4, where v3 was fine. Using laravel 5.3.10:

When running a backup, getting
```
[2016-09-20 20:35:27] local.ERROR: Swift_TransportException: Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required
" in D:\home\firebird\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php:383
Stack trace:
#0 D:\home\firebird\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php(281): Swift_Transport_AbstractSmtpTransport->_assertResponseCode('530 5.7.1 Authe...', Array)
#1 D:\home\firebird\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\EsmtpTransport.php(270): Swift_Transport_AbstractSmtpTransport->executeCommand('MAIL FROM:<hell...', Array, Array)
#2 D:\home\firebird\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\EsmtpTransport.php(348): Swift_Transport_EsmtpTransport->executeCommand('MAIL FROM:<hell...', Array)
#3 D:\home\firebird\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php(416): Swift_Transport_EsmtpTransport->_doMailFromCommand('hello@example.c...')
#4 D:\home\firebird\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php(443): Swift_Transport_AbstractSmtpTransport->_doMailTransaction(Object(Swift_Message), 'hello@example.c...', Array, Array)
#5 D:\home\firebird\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php(176): Swift_Transport_AbstractSmtpTransport->_sendTo(Object(Swift_Message), 'hello@example.c...', Array, Array)
#6 D:\home\firebird\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Mailer.php(85): Swift_Transport_AbstractSmtpTransport->send(Object(Swift_Message), Array)
#7 D:\home\firebird\vendor\laravel\framework\src\Illuminate\Mail\Mailer.php(374): Swift_Mailer->send(Object(Swift_Message), Array)
#8 D:\home\firebird\vendor\laravel\framework\src\Illuminate\Mail\Mailer.php(196): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message))
#9 D:\home\firebird\vendor\laravel\framework\src\Illuminate\Notifications\Channels\MailChannel.php(73): Illuminate\Mail\Mailer->send('notifications::...', Array, Object(Closure))
#10 D:\home\firebird\vendor\laravel\framework\src\Illuminate\Notifications\ChannelManager.php(79): Illuminate\Notifications\Channels\MailChannel->send(Object(Spatie\Backup\Notifications\Notifiable), Object(Spatie\Backup\Notifications\Notifications\BackupHasFailed))
#11 D:\home\firebird\vendor\laravel\framework\src\Illuminate\Notifications\ChannelManager.php(43): Illuminate\Notifications\ChannelManager->sendNow(Array, Object(Spatie\Backup\Notifications\Notifications\BackupHasFailed))
#12 D:\home\firebird\vendor\laravel\framework\src\Illuminate\Notifications\RoutesNotifications.php(18): Illuminate\Notifications\ChannelManager->send(Array, Object(Spatie\Backup\Notifications\Notifications\BackupHasFailed))
#13 D:\home\firebird\vendor\spatie\laravel-backup\src\Notifications\EventHandler.php(33): Spatie\Backup\Notifications\Notifiable->notify(Object(Spatie\Backup\Notifications\Notifications\BackupHasFailed))
#14 [internal function]: Spatie\Backup\Notifications\EventHandler->Spatie\Backup\Notifications\{closure}(Object(Spatie\Backup\Events\BackupHasFailed))
#15 D:\home\firebird\vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php(221): call_user_func_array(Object(Closure), Array)
#16 D:\home\firebird\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php(477): Illuminate\Events\Dispatcher->fire('Spatie\\Backup\\E...')
#17 D:\home\firebird\vendor\spatie\laravel-backup\src\Commands\BackupCommand.php(49): event(Object(Spatie\Backup\Events\BackupHasFailed))
#18 [internal function]: Spatie\Backup\Commands\BackupCommand->handle()
#19 D:\home\firebird\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#20 D:\home\firebird\vendor\laravel\framework\src\Illuminate\Console\Command.php(169): Illuminate\Container\Container->call(Array)
#21 D:\home\firebird\vendor\symfony\console\Command\Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 D:\home\firebird\vendor\laravel\framework\src\Illuminate\Console\Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 D:\home\firebird\vendor\spatie\laravel-backup\src\Commands\BaseCommand.php(22): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 D:\home\firebird\vendor\symfony\console\Application.php(818): Spatie\Backup\Commands\BaseCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 D:\home\firebird\vendor\symfony\console\Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Spatie\Backup\Commands\BackupCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 D:\home\firebird\vendor\symfony\console\Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 D:\home\firebird\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 D:\home\firebird\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 {main}  
```
This is a clean install of Laravel with only Laravel-backup installed as a provider package.

Thanks.

**Comment by freekmurze** [comment]
Can you test if the application can send mail?

**Comment by bridgeport** [comment]
@freekmurze On the installation posted, I downgraded to v3, and it's working great. I have another fresh installation of Laravel 5.3.10 and I just installed Laravel Backup v4. I set it up with some mailtrap.io credentials, and still no backup. Here's the output:

```
$ php artisan backup:run
Starting backup...
Dumping database phoenix...
Backup failed because The dump process failed with exitcode 1 : General error : ''mysqldump'' is not recognized as an internal or external command,
operable program or batch file.
.
#0 D:\home\phoenix\vendor\spatie\db-dumper\src\DbDumper.php(217): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully(Object(Symfony\Component\Process\Process))
#1 D:\home\phoenix\vendor\spatie\db-dumper\src\Databases\MySql.php(88): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul(Object(Symfony\Component\Process\Process), 'D:\\home\\phoenix...')
#2 D:\home\phoenix\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(196): Spatie\DbDumper\Databases\MySql->dumpToFile('D:\\home\\phoenix...')
#3 [internal function]: Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup\{closure}(Object(Spatie\DbDumper\Databases\MySql), 0)
#4 D:\home\phoenix\vendor\laravel\framework\src\Illuminate\Support\Collection.php(597): array_map(Object(Closure), Array, Array)
#5 D:\home\phoenix\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(199): Illuminate\Support\Collection->map(Object(Closure))
#6 D:\home\phoenix\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(131): Spatie\Backup\Tasks\Backup\BackupJob->dumpDatabases('D:\\home\\phoenix...')
#7 D:\home\phoenix\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(111): Spatie\Backup\Tasks\Backup\BackupJob->createBackupManifest()
#8 D:\home\phoenix\vendor\spatie\laravel-backup\src\Commands\BackupCommand.php(43): Spatie\Backup\Tasks\Backup\BackupJob->run()
#9 [internal function]: Spatie\Backup\Commands\BackupCommand->handle()
#10 D:\home\phoenix\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#11 D:\home\phoenix\vendor\laravel\framework\src\Illuminate\Console\Command.php(169): Illuminate\Container\Container->call(Array)
#12 D:\home\phoenix\vendor\symfony\console\Command\Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 D:\home\phoenix\vendor\laravel\framework\src\Illuminate\Console\Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\C
onsoleOutput))
#14 D:\home\phoenix\vendor\spatie\laravel-backup\src\Commands\BaseCommand.php(22): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 D:\home\phoenix\vendor\symfony\console\Application.php(818): Spatie\Backup\Commands\BaseCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 D:\home\phoenix\vendor\symfony\console\Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Spatie\Backup\Commands\BackupCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symf
ony\Component\Console\Output\ConsoleOutput))
#17 D:\home\phoenix\vendor\symfony\console\Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 D:\home\phoenix\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Ou
tput\ConsoleOutput))
#19 D:\home\phoenix\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 {main}
Backup completed!
```

Thanks.

**Comment by freekmurze** [comment]
Please verify that `mysqldump` is installed on your system and that your php cli process allowed to call it.

**Comment by bridgeport** [comment]
> Please verify that mysqldump is installed on your system and that your php cli process allowed to call it.

Yes, `mysqldump` via command line works fine.

**Comment by freekmurze** [comment]
And can you call `mysqldump` via php cli?

**Comment by bridgeport** [comment]
> And can you call `mysqldump` via php cli?

Yes, that seems to work fine. I created the following "backup.php" test file:
```php
<?php
exec("mysqldump -u root -ppassword phoenix", $output);

// For visual output:
echo '<pre> ' . implode("\n", $output) . '</pre>';
```

Here's a partial output of executing the file via command line:
```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

D:\home\phoenix\public\test>php backup.php
Warning: Using a password on the command line interface can be insecure.
<pre> -- MySQL dump 10.13  Distrib 5.6.28, for Win64 (x86_64)
--
-- Host: localhost    Database: phoenix
-- ------------------------------------------------------
-- Server version       5.6.28-log

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
```

**Comment by freekmurze** [comment]
Does this work?

```bash
exec("'mysqldump' -u root -ppassword phoenix", $output);
```

**Comment by bridgeport** [comment]
No that fails with the following:
```
D:\home\phoenix\public\test>php backup.php
''mysqldump'' is not recognized as an internal or external command,
operable program or batch file.
```

But the following succeeds (swapping double quotes for single):
```php
exec('"mysqldump" -u root -ppassword phoenix', $output);
```

**Comment by freekmurze** [comment]
Those quotes are needed in the Unix-world to allow custom paths with spaces.

I'd accept a non-breaking PR with tests that fixes this for Windows users if the code is not too complicated.

**Comment by bridgeport** [comment]
Thanks for looking into this. I have some, but not a lot of experience with git, so I want to avoid putting forth a non-compliant pull request. In the meantime I have v3 to fall back on, which works great. Thanks again for this package.
