### ISSUE TITLE
There is no notification class that can handle event `Spatie\Backup\Events\BackupWasSuccessful`

### ISSUE THREAD

**Issue by aske-cph** [spatie/laravel-backup#322]
Hi, and thanks for a great package! 

I have just upgraded to version 4.
Version 3 worked just fine. 

Version 4 initially works as expected, the zip is copied to an s3 server, but the notification fails. 
So the temp folder is not cleaned which causes the following backups to grow exponentially in size.

I have not created custom or tampered with the notifications, but shouldn't the ones in vendor work out of the box?

I am on PHP 7 and Laravel 5.3.25. and Laravel-backup 4.3.0.

    php artisan backup:run

```
Successfully copied zip to disk named s3.
Copying zip failed because: There is no notification class that can handle event `Spatie\Backup\Events\BackupWasSuccessful`..
Backup failed because There is no notification class that can handle event `Spatie\Backup\Events\BackupHasFailed`..
#0 /home/forge/ft/vendor/spatie/laravel-backup/src/Notifications/EventHandler.php(57): Spatie\Backup\Exceptions\NotificationCouldNotBeSent::noNotifcationClassForEvent(Object(Spatie\Backup\Events\BackupHasFailed))
#1 /home/forge/ft/vendor/spatie/laravel-backup/src/Notifications/EventHandler.php(31): Spatie\Backup\Notifications\EventHandler->determineNotification(Object(Spatie\Backup\Events\BackupHasFailed))
#2 [internal function]: Spatie\Backup\Notifications\EventHandler->Spatie\Backup\Notifications\{closure}(Object(Spatie\Backup\Events\BackupHasFailed))
#3 /home/forge/ft/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(221): call_user_func_array(Object(Closure), Array)
#4 /home/forge/ft/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(478): Illuminate\Events\Dispatcher->fire('Spatie\\Backup\\E...')
#5 /home/forge/ft/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(220): event(Object(Spatie\Backup\Events\BackupHasFailed))
#6 /home/forge/ft/vendor/laravel/framework/src/Illuminate/Support/Collection.php(228): Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup\{closure}(Object(Spatie\Backup\BackupDestination\BackupDestination), 0)
#7 /home/forge/ft/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(222): Illuminate\Support\Collection->each(Object(Closure))
#8 /home/forge/ft/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(121): Spatie\Backup\Tasks\Backup\BackupJob->copyToBackupDestinations('/home/forge/ft/...')
#9 /home/forge/ft/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(43): Spatie\Backup\Tasks\Backup\BackupJob->run()
#10 [internal function]: Spatie\Backup\Commands\BackupCommand->handle()
#11 /home/forge/ft/vendor/laravel/framework/src/Illuminate/Container/Container.php(508): call_user_func_array(Array, Array)
#12 /home/forge/ft/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#13 /home/forge/ft/vendor/symfony/console/Command/Command.php(254): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /home/forge/ft/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /home/forge/ft/vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(22): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /home/forge/ft/vendor/symfony/console/Application.php(820): Spatie\Backup\Commands\BaseCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /home/forge/ft/vendor/symfony/console/Application.php(187): Symfony\Component\Console\Application->doRunCommand(Object(Spatie\Backup\Commands\BackupCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /home/forge/ft/vendor/symfony/console/Application.php(118): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /home/forge/ft/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /home/forge/ft/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 {main}
Backup failed because: There is no notification class that can handle event `Spatie\Backup\Events\BackupHasFailed`..

```

PS:

I have published the laravel-backup config file and not tampered with the notifications part:

```
    'notifications' => [

        'notifications' => [
            \Spatie\Backup\Notifications\Notifications\BackupHasFailed::class         => ['mail'],
            \Spatie\Backup\Notifications\Notifications\UnhealthyBackupWasFound::class => ['mail'],
            \Spatie\Backup\Notifications\Notifications\CleanupHasFailed::class        => ['mail'],
            \Spatie\Backup\Notifications\Notifications\BackupWasSuccessful::class     => ['mail'],
            \Spatie\Backup\Notifications\Notifications\HealthyBackupWasFound::class   => ['mail'],
            \Spatie\Backup\Notifications\Notifications\CleanupWasSuccessful::class    => ['mail'],
        ],

        /*
         * Here you can specify the notifiable to which the notifications should be sent. The default
         * notifiable will use the variables specified in this config file.
         */
        'notifiable' => \Spatie\Backup\Notifications\Notifiable::class,

        'mail' => [
            'to' => 'secretemail@gmail.com',
        ],

        'slack' => [
            'webhook_url' => '',
        ],
    ],
```

**Comment by freekmurze** [comment]
I investigated this issue, but cannot reproduce it. I've checked the casing and the namespaces of both the `\Spatie\Backup\Notifications\Notifications\BackupWasSuccessful` and `Spatie\Backup\Events\BackupWasSuccessful` classes. The name in the config file seems to be ok as well. In my test app, both the event and the notification are fired without any problems.

Could you try to debug [the `determineNotification function](https://github.com/spatie/laravel-backup/blob/30c8bdc/src/Notifications/EventHandler.php#L44-L61) in your project? [These lines](https://github.com/spatie/laravel-backup/blob/30c8bdc/src/Notifications/EventHandler.php#L51-L53) are of interest. Try to determine what the value of `$eventName` is and which `notificationName`s it loops through.

**Comment by aske-cph** [comment]
Thanks for your response!

I dd'd the eventname and figured out i had not changed my scheduler path in Forge after transitioning to Envoyer. 

My apologies. Maybe the other guy with the same issue has the same solution. Either way this can be closed now!

**Comment by freekmurze** [comment]
No problem, have fun using the package!

**Comment by munkhorgil** [comment]
When I try to backup, It throws exact same problem as above.
`There is no notification class that can handle event `Spatie\Backup\Events\BackupHasFailed`
Somehow it successfully backup

**Comment by bhaidar** [comment]
Hello @freekmurze 
I am using this package on Google Cloud App Engine by calling the following:

```
  \Artisan::call('backup:run',[
                '--only-db' => true,
            ]);
```

However, I got the following errors:

```
There is no notification class that can handle event `Spatie\Backup\Events\BackupHasFailed`. {"exception":"[object] (Spatie\\Backup\\Exceptions\\NotificationCouldNotBeSent(code: 0): There is no notification class that can handle event `Spatie\\Backup\\Events\\BackupHasFailed`. at /app/vendor/spatie/laravel-backup/src/Exceptions/NotificationCouldNotBeSent.php:13)
[stacktrace]
#0 /app/vendor/spatie/laravel-backup/src/Notifications/EventHandler.php(57): Spatie\\Backup\\Exceptions\\NotificationCouldNotBeSent::noNotificationClassForEvent(Object(Spatie\\Backup\\Events\\BackupHasFailed))
#1 /app/vendor/spatie/laravel-backup/src/Notifications/EventHandler.php(31): Spatie\\Backup\\Notifications\\EventHandler->determineNotification(Object(Spatie\\Backup\\Events\\BackupHasFailed))
#2 /app/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(392): Spatie\\Backup\\Notifications\\EventHandler->Spatie\\Backup\\Notifications\\{closure}(Object(Spatie\\Backup\\Events\\BackupHasFailed))
#3 /app/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(237): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Spatie\\\\Backup\\\\E...', Array)
#4 /app/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(450): Illuminate\\Events\\Dispatcher->dispatch('Spatie\\\\Backup\\\\E...')
#5 /app/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(285): event(Object(Spatie\\Backup\\Events\\BackupHasFailed))
#6 /app/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(656): Spatie\\Backup\\Tasks\\Backup\\BackupJob->Spatie\\Backup\\Tasks\\Backup\\{closure}()
#7 /app/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(288): rescue(Object(Closure), Object(Closure))
#8 /app/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(159): Spatie\\Backup\\Tasks\\Backup\\BackupJob->sendNotification(Object(Spatie\\Backup\\Events\\BackupHasFailed))
#9 /app/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(56): Spatie\\Backup\\Tasks\\Backup\\BackupJob->run()
#10 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Spatie\\Backup\\Commands\\BackupCommand->handle()
#11 /app/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#12 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#13 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#14 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(614): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#15 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call(Array)
#16 /app/vendor/symfony/console/Command/Command.php(288): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#17 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#18 /app/vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(16): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#19 /app/vendor/symfony/console/Application.php(974): Spatie\\Backup\\Commands\\BaseCommand->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#20 /app/vendor/symfony/console/Application.php(291): Symfony\\Component\\Console\\Application->doRunCommand(Object(Spatie\\Backup\\Commands\\BackupCommand), Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#21 /app/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#22 /app/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#23 /app/vendor/laravel/framework/src/Illuminate/Console/Application.php(184): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#24 /app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(263): Illuminate\\Console\\Application->call('backup:run', Array, NULL)
#25 /app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Foundation\\Console\\Kernel->call('backup:run', Array)
#26 /app/app/Http/Controllers/Others/SetupController.php(27): Illuminate\\Support\\Facades\\Facade::__callStatic('call', Array)
#27 /app/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Others\\SetupController->__invoke(Object(Illuminate\\Http\\Request))
#28 /app/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('__invoke', Array)
#29 /app/vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Others\\SetupController), '__invoke')
#30 /app/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
#31 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
#32 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 /app/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /app/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /app/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /app/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#41 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /app/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /app/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#48 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#49 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#50 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#51 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#52 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#53 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#65 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#66 /app/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#67 {main}
```

**Comment by ismaail** [comment]
To solve the issue for me was to uncomment the line with `CleanupWasSuccessfulNotification` in `config/backup.php`

```php
'notifications' => [

    'notifications' => [
        //...
        \Spatie\Backup\Notifications\Notifications\CleanupWasSuccessfulNotification::class => ['mail'],
    ],
```

**Comment by OzanKurt** [comment]
@freekmurze Here is the dump:

```
dd($lookingForNotificationClass, $this->config->get('backup.notifications.notifications'));

"BackupHasFailedNotification"
array:6 [
  "Spatie\Backup\Events\BackupHasFailed" => array:1 [
    0 => "slack"
  ]
  "Spatie\Backup\Events\UnhealthyBackupWasFound" => array:1 [
    0 => "slack"
  ]
  "Spatie\Backup\Events\CleanupHasFailed" => array:1 [
    0 => "slack"
  ]
  "Spatie\Backup\Events\BackupWasSuccessful" => array:1 [
    0 => "slack"
  ]
  "Spatie\Backup\Events\HealthyBackupWasFound" => array:1 [
    0 => "slack"
  ]
  "Spatie\Backup\Events\CleanupWasSuccessful" => array:1 [
    0 => "slack"
  ]
]
```

**Comment by OzanKurt** [comment]
I just copied the whole config file and updated it, now it works.

**Comment by fredbradley** [comment]
In case anyone else got here because of this same error, it turns out that at some point in the upgrade path (I've gone straight from v6 to v8) the names of the Notification classes have changed to have "Notification" suffixed on the end of them. 

*Change:*
```
\Spatie\Backup\Notifications\Notifications\BackupHasFailed::class => ['mail', 'slack'],
\Spatie\Backup\Notifications\Notifications\UnhealthyBackupWasFound::class => ['mail', 'slack'],
\Spatie\Backup\Notifications\Notifications\CleanupHasFailed::class => ['mail', 'slack'],
\Spatie\Backup\Notifications\Notifications\BackupWasSuccessful::class => ['mail'],
\Spatie\Backup\Notifications\Notifications\HealthyBackupWasFound::class => ['mail'],
\Spatie\Backup\Notifications\Notifications\CleanupWasSuccessful::class => ['mail'],
```

*To this:*
```
\Spatie\Backup\Notifications\Notifications\BackupHasFailedNotification::class => ['mail', 'slack'],
\Spatie\Backup\Notifications\Notifications\UnhealthyBackupWasFoundNotification::class => ['mail', 'slack'],
\Spatie\Backup\Notifications\Notifications\CleanupHasFailedNotification::class => ['mail', 'slack'],
\Spatie\Backup\Notifications\Notifications\BackupWasSuccessfulNotification::class => ['mail'],
\Spatie\Backup\Notifications\Notifications\HealthyBackupWasFoundNotification::class => ['mail'],
\Spatie\Backup\Notifications\Notifications\CleanupWasSuccessfulNotification::class => ['mail'],
```

Keeping us on our toes! 😀

**Comment by wadimsewo** [comment]
> UnhealthyBackupWasFoundNotification

If you create your own notifications, they must be identical to the original. In my case:

From:
`            \App\Notifications\Backup\BaseNotifications\UnhealthyBackupWasFound::class => [\App\Notifications\Backup\UnhealthyBackupWasFoundNotification::class],
`
To:
`            \App\Notifications\Backup\BaseNotifications\UnhealthyBackupWasFoundNotification::class => [\App\Notifications\Backup\UnhealthyBackupWasFoundNotification::class],
`

**Comment by lungu-catalin** [comment]
Hi there,

I had the same issue but in my case the problem was the wrong class names for notifications.
        'notifications' => [
            \Spatie\Backup\Notifications\Notifications\BackupHasFailed::class         => ['mail'],
            \Spatie\Backup\Notifications\Notifications\UnhealthyBackupWasFound::class => ['mail'],
            \Spatie\Backup\Notifications\Notifications\CleanupHasFailed::class        => ['mail'],
            \Spatie\Backup\Notifications\Notifications\BackupWasSuccessful::class     => ['mail'],
            \Spatie\Backup\Notifications\Notifications\HealthyBackupWasFound::class   => ['mail'],
            \Spatie\Backup\Notifications\Notifications\CleanupWasSuccessful::class    => ['mail'],
        ],

The new names should be:
        'notifications' => [
            \Spatie\Backup\Notifications\Notifications\BackupHasFailedNotification::class => ['mail'],
            \Spatie\Backup\Notifications\Notifications\UnhealthyBackupWasFoundNotification::class => ['mail'],
            \Spatie\Backup\Notifications\Notifications\CleanupHasFailedNotification::class => ['mail'],
            \Spatie\Backup\Notifications\Notifications\BackupWasSuccessfulNotification::class => ['mail'],
            \Spatie\Backup\Notifications\Notifications\HealthyBackupWasFoundNotification::class => ['mail'],
            \Spatie\Backup\Notifications\Notifications\CleanupWasSuccessfulNotification::class => ['mail'],
        ],

Perhaps after update I didn't republish the config file.

**Comment by nzian** [comment]
> In case anyone else got here because of this same error, it turns out that at some point in the upgrade path (I've gone straight from v6 to v8) the names of the Notification classes have changed to have "Notification" suffixed on the end of them.
> 
> _Change:_
> 
> ```
> \Spatie\Backup\Notifications\Notifications\BackupHasFailed::class => ['mail', 'slack'],
> \Spatie\Backup\Notifications\Notifications\UnhealthyBackupWasFound::class => ['mail', 'slack'],
> \Spatie\Backup\Notifications\Notifications\CleanupHasFailed::class => ['mail', 'slack'],
> \Spatie\Backup\Notifications\Notifications\BackupWasSuccessful::class => ['mail'],
> \Spatie\Backup\Notifications\Notifications\HealthyBackupWasFound::class => ['mail'],
> \Spatie\Backup\Notifications\Notifications\CleanupWasSuccessful::class => ['mail'],
> ```
> 
> _To this:_
> 
> ```
> \Spatie\Backup\Notifications\Notifications\BackupHasFailedNotification::class => ['mail', 'slack'],
> \Spatie\Backup\Notifications\Notifications\UnhealthyBackupWasFoundNotification::class => ['mail', 'slack'],
> \Spatie\Backup\Notifications\Notifications\CleanupHasFailedNotification::class => ['mail', 'slack'],
> \Spatie\Backup\Notifications\Notifications\BackupWasSuccessfulNotification::class => ['mail'],
> \Spatie\Backup\Notifications\Notifications\HealthyBackupWasFoundNotification::class => ['mail'],
> \Spatie\Backup\Notifications\Notifications\CleanupWasSuccessfulNotification::class => ['mail'],
> ```
> 
> Keeping us on our toes! 😀

You just save my time. I am really grateful. and Feel lucky that read your comment. Thank you.

**Comment by georgknabl** [comment]
In case anyone, just like me, came here for the same error but with another issue that was not resolved by the solution outlined by @fredbradley, I hope this helps.
The issue in my code that triggered the error was that I wanted to suppress some notifications, such as BackupWasSuccessfulNotification, so I commented-out the whole line. To solve this, leave the line as is and just remove the notification channels from the array.

Change:
`// \Spatie\Backup\Notifications\Notifications\BackupWasSuccessful::class => ['mail'],`

To this:
`\Spatie\Backup\Notifications\Notifications\BackupWasSuccessful::class => [],`

**Comment by MattDevTec** [comment]
Which file do i make those changes to. Sorry if i seem stupid
