### ISSUE TITLE
Backup Failing after Upgrade to Laravel 5.4

### ISSUE THREAD

**Issue by arnoldjp57** [spatie/laravel-backup#361]
I have the backup configured to go to dropbox and its was working 100% till I migrated to Laravel 5.4.
php artisan backup:run now throws the following error ...
```
php artisan backup:run
Starting backup...
Dumping database mysql23..
Backup failed because The dump process failed with exitcode 2 : Misuse of shell builtins : sh: 1: cannot create /tmp/0.68140100 1486036553/db-dumps/mysql123.sql: Directory nonexistent
```
The dropbox is working for other stuff in my app ...

**Comment by freekmurze** [comment]
The error is caused by the space in the temporary directory the package is used. Run `composer update` again to fix the problem.

**Comment by arnoldjp57** [comment]
composer update runs and error still occurs .....

**Comment by freekmurze** [comment]
Tagged another fix a minute ago.

Wait a couple of more minutes, run `composer update` again and verify with `composer show` that `v1.1.1` of `spatie/temporary-directory` has been pulled in.

**Comment by arnoldjp57** [comment]
Tried that .... 1.1.1 came down, bust still error
```
composer show | grep spatie
spatie/db-dumper                      2.4.1       Dump databases
spatie/laravel-backup                 4.4.3       A Laravel 5 package to ba...
spatie/laravel-translation-loader     1.1.0       Store your language lines...
spatie/temporary-directory            1.0.0       The `temporary-directory`...
odierhp@odiedev:/var/www/html/odie54$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 2 updates, 0 removals
  - Updating spatie/temporary-directory (1.0.0 => 1.1.1) Downloading: Connecting Downloading: 100%         
  - Updating spatie/laravel-backup (4.4.3 => 4.4.4) Downloading: 100%         
Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
Generating optimized class loader
The compiled services file has been removed.
odierhp@odiedev:/var/www/html/odie54$ php artisan backup:run
Starting backup...
Dumping database odierhp...
Backup failed because The dump process failed with exitcode 2 : Misuse of shell builtins : sh: 1: cannot create /tmp/0.945905001486038799/db-dumps/odierhp.sql: Directory nonexistent
.
#0 /var/www/html/odie54/vendor/spatie/db-dumper/src/DbDumper.php(222): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully(Object(Symfony\Component\Process\Process))
#1 /var/www/html/odie54/vendor/spatie/db-dumper/src/Databases/MySql.php(111): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul(Object(Symfony\Component\Process\Process), '/tmp/0.94590500...')
#2 /var/www/html/odie54/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(201): Spatie\DbDumper\Databases\MySql->dumpToFile('/tmp/0.94590500...')
#3 [internal function]: Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup\{closure}(Object(Spatie\DbDumper\Databases\MySql), 0)
#4 /var/www/html/odie54/vendor/laravel/framework/src/Illuminate/Support/Collection.php(636): array_map(Object(Closure), Array, Array)
#5 /var/www/html/odie54/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(204): Illuminate\Support\Collection->map(Object(Closure))
#6 /var/www/html/odie54/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(134): Spatie\Backup\Tasks\Backup\BackupJob->dumpDatabases('/tmp/0.94590500...')
#7 /var/www/html/odie54/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(114): Spatie\Backup\Tasks\Backup\BackupJob->createBackupManifest()
#8 /var/www/html/odie54/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(43): Spatie\Backup\Tasks\Backup\BackupJob->run()

```

**Comment by freekmurze** [comment]
You're probably on Windows.

Is the `/tmp/` directory writeable?

**Comment by freekmurze** [comment]
Looking into a fix now.

**Comment by arnoldjp57** [comment]
ubuntu 16.04
/tmp is 

```
ls -ld /tmp
drwxrwxrwt 33 root root 12288 Feb  2 14:29 /tmp

```

**Comment by arnoldjp57** [comment]
Oh Yes ... Great Product, easy to use ... One question, how to I add the option to flush the binary log when the backup happens ....

**Comment by arnoldjp57** [comment]
As an idea ..... I am flushing the binary logs every hour and popping them into dropbox ... So, if I ever have a catastrophe and need to rebuild and restore, I can get back to within and hour max of the last transaction.

**Comment by arnoldjp57** [comment]
Fixed ..... Thanks Guys :)
