### ISSUE TITLE
backup:run ends in 'Copying zip failed because: Target' error

### ISSUE THREAD

**Issue by JPT62089** [spatie/laravel-backup#427]
I just installed this and have been trying to get it to back up my database to S3. Whenever I run the backup it looks like it successfully saves the backup in S3 but the run ends with the following error. Any thoughts as to why I'm getting it? I'm on Laravel 5.4.21

```Bash
Copying zip failed because: Target [Illuminate\Contracts\Notifications\Dispatcher] is not instantiable..
Backup failed because Target [Illuminate\Contracts\Notifications\Dispatcher] is not instantiable..
#0 ./vendor/laravel/framework/src/Illuminate/Container/Container.php(725): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 ./vendor/laravel/framework/src/Illuminate/Container/Container.php(598): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 ./vendor/laravel/framework/src/Illuminate/Container/Container.php(567): Illuminate\Container\Container->resolve('Illuminate\\Cont...')
#3 ./vendor/laravel/framework/src/Illuminate/Foundation/Application.php(708): Illuminate\Container\Container->make('Illuminate\\Cont...')
#4 ./vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(107): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#5 ./vendor/laravel/framework/src/Illuminate/Notifications/RoutesNotifications.php(18): app('Illuminate\\Cont...')
#6 ./vendor/spatie/laravel-backup/src/Notifications/EventHandler.php(33): Spatie\Backup\Notifications\Notifiable->notify(Object(Spatie\Backup\Notifications\Notifications\BackupHasFailed))
#7 ./vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(334): Spatie\Backup\Notifications\EventHandler->Spatie\Backup\Notifications\{closure}(Object(Spatie\Backup\Events\BackupHasFailed))
#8 ./vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(199): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('Spatie\\Backup\\E...', Array)
#9 ./vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(482): Illuminate\Events\Dispatcher->dispatch('Spatie\\Backup\\E...')
#10 ./vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(231): event(Object(Spatie\Backup\Events\BackupHasFailed))
#11 ./vendor/laravel/framework/src/Illuminate/Support/Collection.php(260): Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup\{closure}(Object(Spatie\Backup\BackupDestination\BackupDestination), 0)
#12 ./vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(233): Illuminate\Support\Collection->each(Object(Closure))
#13 ./vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(125): Spatie\Backup\Tasks\Backup\BackupJob->copyToBackupDestinations('/path/to/laravel....')
#14 ./vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(43): Spatie\Backup\Tasks\Backup\BackupJob->run()
#15 [internal function]: Spatie\Backup\Commands\BackupCommand->handle()
#16 ./vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#17 ./vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#18 ./vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#19 ./vendor/laravel/framework/src/Illuminate/Container/Container.php(531): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#20 ./vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#21 ./vendor/symfony/console/Command/Command.php(262): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#22 ./vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#23 ./vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(22): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 ./vendor/symfony/console/Application.php(826): Spatie\Backup\Commands\BaseCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 ./vendor/symfony/console/Application.php(190): Symfony\Component\Console\Application->doRunCommand(Object(Spatie\Backup\Commands\BackupCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 ./vendor/symfony/console/Application.php(121): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 ./vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(123): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 ./artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 {main}
Backup failed because: Target [Illuminate\Contracts\Notifications\Dispatcher] is not instantiable..
```

**Comment by JPT62089** [comment]
Resolved...

For some reason I didn't have the Notifications service provider and facade registered in app.php
