### ISSUE TITLE
Copying zip failed because: There is no disk set for the backup destination

### ISSUE THREAD

**Issue by IbrahimAssad** [spatie/laravel-backup#430]
I got this exception when try to create backup using ` php artisan backup:run --only-db `

could you please let me know if there is any missing attribute in configuration ..

```
Starting backup...
Dumping database my_db...
Determining files to backup...
Zipping 1 files...
Created zip containing 1 files. Size is 3.67 KB
Copying zip to disk named local...
Copying zip failed because: There is no disk set for the backup destination.

Backup failed because There is no notification class that can handle event `Spatie\Backup\Events\BackupHasFailed`..
#0 /var/www/someProject/vendor/spatie/laravel-backup/src/Notifications/EventHandler.php(57): Spatie\Backup\Exceptions\NotificationCouldNotBeSent::noNotifcationClassForEvent(Object(Spatie\Backup\Events\BackupHasFailed))
#1 /var/www/someProject/vendor/spatie/laravel-backup/src/Notifications/EventHandler.php(31): Spatie\Backup\Notifications\EventHandler->determineNotification(Object(Spatie\Backup\Events\BackupHasFailed))
#2 [internal function]: Spatie\Backup\Notifications\EventHandler->Spatie\Backup\Notifications\{closure}(Object(Spatie\Backup\Events\BackupHasFailed))
#3 /var/www/someProject/vendor/illuminate/events/Dispatcher.php(221): call_user_func_array(Object(Closure), Array)
#4 /var/www/someProject/vendor/laravel/lumen-framework/src/helpers.php(185): Illuminate\Events\Dispatcher->fire('Spatie\\Backup\\E...', Array, false)
#5 /var/www/someProject/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(230): event(Object(Spatie\Backup\Events\BackupHasFailed))
#6 /var/www/someProject/vendor/illuminate/support/Collection.php(228): Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup\{closure}(Object(Spatie\Backup\BackupDestination\BackupDestination), 0)
#7 /var/www/someProject/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(232): Illuminate\Support\Collection->each(Object(Closure))
#8 /var/www/someProject/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(125): Spatie\Backup\Tasks\Backup\BackupJob->copyToBackupDestinations('/var/www/somePr...')
#9 /var/www/someProject/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(43): Spatie\Backup\Tasks\Backup\BackupJob->run()
#10 [internal function]: Spatie\Backup\Commands\BackupCommand->handle()
#11 /var/www/someProject/vendor/illuminate/container/Container.php(508): call_user_func_array(Array, Array)
#12 /var/www/someProject/vendor/illuminate/console/Command.php(169): Illuminate\Container\Container->call(Array)
#13 /var/www/someProject/vendor/symfony/console/Command/Command.php(261): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/someProject/vendor/illuminate/console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/someProject/vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(22): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/someProject/vendor/symfony/console/Application.php(817): Spatie\Backup\Commands\BaseCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/someProject/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Spatie\Backup\Commands\BackupCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/someProject/vendor/symfony/console/Application.php(116): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/someProject/vendor/laravel/lumen-framework/src/Console/Kernel.php(83): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/someProject/artisan(35): Laravel\Lumen\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 {main}
Backup failed because: There is no notification class that can handle event `Spatie\Backup\Events\BackupHasFailed`..


  [Spatie\Backup\Exceptions\NotificationCouldNotBeSent]
  There is no notification class that can handle event `Spatie\Backup\Events\BackupHasFa
  iled`.


```

and laravel-backup.php file

```
<?php


return [

    'backup'         => [

        /*
        * The name of this application. You can use this name to monitor
        * the backups.
        */
        'name' => 'My-backup',

        'source' => [

            'files'     => [

                /*
                * The list of directories and files that will be included in the backup.
                */
                'include'     => [
                    base_path(),
                ],

                /*
                * These directories and files will be excluded from the backup.
                *
                * Directories used by the backup process will automatically be excluded.
                */
                'exclude'     => [
                    base_path('vendor'),
                    base_path('node_modules'),
                ],

                /*
                * Determines if symlinks should be followed.
                */
                'followLinks' => false,
            ],

            /*
            * The names of the connections to the databases that should be backed up
            * Only MySQL and PostgreSQL databases are supported.
            */
            'databases' => [
                'mysql',
            ],
        ],

        'destination' => [

            /*
            * The filename prefix used for the backup zip file.
            */
            'filename_prefix' => '_ibrahim__',

            /*
            * The disk names on which the backups will be stored.
            */
            'disks'           => [
                'local',
            ],
        ],
    ],


    /*
    * You can get notified when specific events occur. Out of the box you can use 'mail' and 'slack'.
    * For Slack you need to install guzzlehttp/guzzle.
    *
    * You can also use your own notification classes, just make sure the class is named after one of
    * the `Spatie\Backup\Events` classes.
    */
    'notifications'  => [

        'notifications' => [
            \Spatie\Backup\Notifications\Notifications\BackupHasFailed::class         => ['mail'],
            \Spatie\Backup\Notifications\Notifications\UnhealthyBackupWasFound::class => ['mail'],
            \Spatie\Backup\Notifications\Notifications\CleanupHasFailed::class        => ['mail'],
            \Spatie\Backup\Notifications\Notifications\BackupWasSuccessful::class     => ['mail'],
            \Spatie\Backup\Notifications\Notifications\HealthyBackupWasFound::class   => ['mail'],
            \Spatie\Backup\Notifications\Notifications\CleanupWasSuccessful::class    => ['mail'],
        ],

        /*
        * Here you can specify the notifiable to which the notifications should be sent. The default
        * notifiable will use the variables specified in this config file.
        */
       // 'notifiable'    => \Spatie\Backup\Notifications\Notifiable::class,

        'mail' => [
            'to' => 'ibrahim.assad@tajawal.com',
        ],

        'slack' => [
            'webhook_url' => '',
        ],
    ],

    /*
    * Here you can specify which backups should be monitored.
    * If a backup does not meet the specified requirements the
    * UnHealthyBackupWasFound event will be fired.
    */
    'monitorBackups' => [
        [
            'name'                                   => env('APP_URL'),
            'disks'                                  => ['local'],
            'newestBackupsShouldNotBeOlderThanDays'  => 1,
            'storageUsedMayNotBeHigherThanMegabytes' => 50000,
        ],

        /*
        [
        'name' => 'name of the second app',
        'disks' => ['local', 's3'],
        'newestBackupsShouldNotBeOlderThanDays' => 1,
        'storageUsedMayNotBeHigherThanMegabytes' => 5000,
        ],
        */
    ],


    'cleanup' => [
        /*
        * The strategy that will be used to cleanup old backups. The default strategy
        * will keep all backups for a certain amount of days. After that period only
        * a daily backup will be kept. After that period only weekly backups will
        * be kept and so on.
        *
        * No matter how you configure it the default strategy will never
        * delete the newest backup.
        */
        'strategy' => \Spatie\Backup\Tasks\Cleanup\Strategies\DefaultStrategy::class,

        'defaultStrategy' => [

            /*
            * The number of days for which backups must be kept.
            */
            'keepAllBackupsForDays'                         => 7,

            /*
            * The number of days for which daily backups must be kept.
            */
            'keepDailyBackupsForDays'                       => 16,

            /*
            * The number of weeks for which one weekly backup must be kept.
            */
            'keepWeeklyBackupsForWeeks'                     => 8,

            /*
            * The number of months for which one monthly backup must be kept.
            */
            'keepMonthlyBackupsForMonths'                   => 4,

            /*
            * The number of years for which one yearly backup must be kept.
            */
            'keepYearlyBackupsForYears'                     => 2,

            /*
            * After cleaning up the backups remove the oldest backup until
            * this amount of megabytes has been reached.
            */
            'deleteOldestBackupsWhenUsingMoreMegabytesThan' => 5000,
        ],
    ],
];
```

**Comment by freekmurze** [comment]
Did you define a disk named `local` in `config/filesystems.php`?

**Comment by IbrahimAssad** [comment]
yes 
```
'disks' => [

        'local' => [
            'driver' => 'local',
            'root'   => storage_path(),
        ]
]
```

**Comment by freekmurze** [comment]
Does `php artisan backup:run` work?

**Comment by IbrahimAssad** [comment]
same issue

**Comment by freekmurze** [comment]
Could you install the package in a vanilla Laravel app and test if it works there?
