### ISSUE TITLE
Backups not running for clean install of Laravel 5.5

### ISSUE THREAD

**Issue by seandelaney** [spatie/laravel-backup#519]
Clean install of Laravel 5.5 with this library.

When I try running a backup I get the following:

```
seandelaney@UNKNOWN ~/Sites/cms (master) $ php artisan backup:run --only-db
Starting backup...
Dumping database cms...
Backup failed because The dump process failed with exitcode 127 : Command not found : sh: mysqldump: command not found
.
#0 /Users/seandelaney/Sites/cms/vendor/spatie/db-dumper/src/DbDumper.php(222): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully(Object(Symfony\Component\Process\Process))
#1 /Users/seandelaney/Sites/cms/vendor/spatie/db-dumper/src/Databases/MySql.php(129): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul(Object(Symfony\Component\Process\Process), '/Users/seandela...')
#2 /Users/seandelaney/Sites/cms/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(219): Spatie\DbDumper\Databases\MySql->dumpToFile('/Users/seandela...')
#3 [internal function]: Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup\{closure}(Object(Spatie\DbDumper\Databases\MySql), 0)
#4 /Users/seandelaney/Sites/cms/vendor/laravel/framework/src/Illuminate/Support/Collection.php(833): array_map(Object(Closure), Array, Array)
#5 /Users/seandelaney/Sites/cms/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(230): Illuminate\Support\Collection->map(Object(Closure))
#6 /Users/seandelaney/Sites/cms/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(149): Spatie\Backup\Tasks\Backup\BackupJob->dumpDatabases()
#7 /Users/seandelaney/Sites/cms/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(129): Spatie\Backup\Tasks\Backup\BackupJob->createBackupManifest()
#8 /Users/seandelaney/Sites/cms/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(49): Spatie\Backup\Tasks\Backup\BackupJob->run()
#9 [internal function]: Spatie\Backup\Commands\BackupCommand->handle()
#10 /Users/seandelaney/Sites/cms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#11 /Users/seandelaney/Sites/cms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#12 /Users/seandelaney/Sites/cms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#13 /Users/seandelaney/Sites/cms/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#14 /Users/seandelaney/Sites/cms/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Illuminate\Container\Container->call(Array)
#15 /Users/seandelaney/Sites/cms/vendor/symfony/console/Command/Command.php(264): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#16 /Users/seandelaney/Sites/cms/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#17 /Users/seandelaney/Sites/cms/vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(22): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /Users/seandelaney/Sites/cms/vendor/symfony/console/Application.php(888): Spatie\Backup\Commands\BaseCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /Users/seandelaney/Sites/cms/vendor/symfony/console/Application.php(224): Symfony\Component\Console\Application->doRunCommand(Object(Spatie\Backup\Commands\BackupCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /Users/seandelaney/Sites/cms/vendor/symfony/console/Application.php(125): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /Users/seandelaney/Sites/cms/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /Users/seandelaney/Sites/cms/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /Users/seandelaney/Sites/cms/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 {main}
Backup completed!
```

`mysqldump` is installed and working fine.

```
seandelaney@UNKNOWN ~/Sites/cms (master) $ mysqldump
Warning: Using a password on the command line interface can be insecure.
Usage: mysqldump [OPTIONS] database [tables]
OR     mysqldump [OPTIONS] --databases [OPTIONS] DB1 [DB2 DB3...]
OR     mysqldump [OPTIONS] --all-databases [OPTIONS]
For more options, use mysqldump --help
seandelaney@UNKNOWN ~/Sites/cms (master) $
```

I'm running:

- MacOS Sierra.
- PHP 7.1.8.
- MySQL: 5.6.35

Any ideas?

**Comment by seandelaney** [comment]
Reinstalling MySQL locally fixed the issue.
