### ISSUE TITLE
FTP backup error

### ISSUE THREAD

**Issue by oriceon** [spatie/laravel-backup#577]
Hi there! I received an error when i trying to backup on a FTP even if backup was successfuly uploaded to FTP.

I'm using Laravel 5.5 on a Windows 10.

```
Copying zip to disk named ftp...
Successfully copied zip to disk named ftp.
Copying zip failed because: Could not connect to host: WAN_IP, port:PORT.
Backup failed because Could not connect to host: WAN_IP, port:PORT.
#0 app\vendor\league\flysystem\src\Adapter\AbstractFtpAdapter.php(582): League\Flysystem\Adapter\Ftp->connect()
#1 app\vendor\league\flysystem\src\Adapter\Ftp.php(562): League\Flysystem\Adapter\AbstractFtpAdapter->getConnection()
#2 app\vendor\league\flysystem\src\Adapter\Ftp.php(498): League\Flysystem\Adapter\Ftp->ftpRawlist('-alnR', 'Backups')
#3 app\vendor\league\flysystem\src\Adapter\AbstractFtpAdapter.php(322): League\Flysystem\Adapter\Ftp->listDirectoryContents('Backups', true)
#4 app\vendor\league\flysystem\src\Filesystem.php(271): League\Flysystem\Adapter\AbstractFtpAdapter->listContents('Backups', true)
#5 app\vendor\laravel\framework\src\Illuminate\Filesystem\FilesystemAdapter.php(472): League\Flysystem\Filesystem->listContents('Backups', true)
#6 app\vendor\laravel\framework\src\Illuminate\Filesystem\FilesystemAdapter.php(485): Illuminate\Filesystem\FilesystemAdapter->files('Backups', true)
```

**Comment by freekmurze** [comment]
Seems to me that this problem is not with this package but either with your server setup or the [Flysystem FTP adapter](https://flysystem.thephpleague.com/adapter/ftp/).
