### ISSUE TITLE
unknown database when running backup

### ISSUE THREAD

**Issue by cloudbluedigital** [spatie/laravel-backup#590]
Hi I get this error

```
vagrant@liveandnow:~/liveandnow$ php artisan backup:run --only-db
Starting backup...
Dumping database liveoldham...
Backup failed because The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Got error: 1049: Unknown database 'liveoldham' when selecting the database
.
#0 /home/vagrant/liveandnow/vendor/spatie/db-dumper/src/DbDumper.php(222): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully(Object(Symfony\Component\Process\Process))
#1 /home/vagrant/liveandnow/vendor/spatie/db-dumper/src/Databases/MySql.php(129): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul(Object(Symfony\Component\Process\Process), '/home/vagrant/l...')
#2 /home/vagrant/liveandnow/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(219): Spatie\DbDumper\Databases\MySql->dumpToFile('/home/vagrant/l...')
#3 [internal function]: Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup\{closure}(Object(Spatie\DbDumper\Databases\MySql), 0)
#4 /home/vagrant/liveandnow/vendor/laravel/framework/src/Illuminate/Support/Collection.php(847): array_map(Object(Closure), Array, Array)
#5 /home/vagrant/liveandnow/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(230): Illuminate\Support\Collection->map(Object(Closure))
#6 /home/vagrant/liveandnow/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(149): Spatie\Backup\Tasks\Backup\BackupJob->dumpDatabases()
#7 /home/vagrant/liveandnow/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(129): Spatie\Backup\Tasks\Backup\BackupJob->createBackupManifest()
#8 /home/vagrant/liveandnow/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(49): Spatie\Backup\Tasks\Backup\BackupJob->run()
#9 [internal function]: Spatie\Backup\Commands\BackupCommand->handle()
#10 /home/vagrant/liveandnow/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#11 /home/vagrant/liveandnow/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#12 /home/vagrant/liveandnow/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#13 /home/vagrant/liveandnow/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#14 /home/vagrant/liveandnow/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#15 /home/vagrant/liveandnow/vendor/symfony/console/Command/Command.php(252): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#16 /home/vagrant/liveandnow/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#17 /home/vagrant/liveandnow/vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(22): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /home/vagrant/liveandnow/vendor/symfony/console/Application.php(936): Spatie\Backup\Commands\BaseCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /home/vagrant/liveandnow/vendor/symfony/console/Application.php(240): Symfony\Component\Console\Application->doRunCommand(Object(Spatie\Backup\Commands\BackupCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /home/vagrant/liveandnow/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /home/vagrant/liveandnow/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /home/vagrant/liveandnow/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /home/vagrant/liveandnow/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 {main}
Backup completed!
```

It is using mysql driver which I know is setup properly as I can use the site and perform queries, it is just failing on the backup

**Comment by cloudbluedigital** [comment]
just to clarify, it is trying to connect to my local database I believe while I am using RDS

**Comment by freekmurze** [comment]
Seems like it can't find your db

```
Unknown database 'liveoldham' when selecting the database
```

**Comment by tfpdeveloper** [comment]
I am having same issue with Amazon RDS, 
I am trying to backup RDS Database but it's trying to connect to localhost.

I tried to backup Azure database and it did it successfully.
I also ensured that I do have database with given name in RDS. If I keep database with same name in localhost then it will backup local database otherwise will give above error.

Somehow, it's ignoring the rds host

**Comment by brnmonteiro** [comment]
Runing in RDS:

`Backup failed because The dump process failed with exitcode 2 : Misuse of shell builtins : Warning: A partial dump from a server that has GTIDs will by default include the GTIDs of all transactions, even those that changed suppressed parts of the database. If you don't want to restore GTIDs, pass --set-gtid-purged=OFF. To make a complete dump, pass --all-databases --triggers --routines --events.

**Comment by Oxicode** [comment]
> Runing in RDS:
> 
> `Backup failed because The dump process failed with exitcode 2 : Misuse of shell builtins : Warning: A partial dump from a server that has GTIDs will by default include the GTIDs of all transactions, even those that changed suppressed parts of the database. If you don't want to restore GTIDs, pass --set-gtid-purged=OFF. To make a complete dump, pass --all-databases --triggers --routines --events.`

me too
