### ISSUE TITLE
Doesn't Return Correct Exit Code in Some Situations

### ISSUE THREAD

**Issue by mdavis1982** [spatie/laravel-backup#618]
We're using this package as part of a Deployment Hook in Envoyer to take a backup of our site before a deploy happens.

We did some work in #606 and #607 to help return the correct exit codes in most situations so that our deployment would fail if the backup did not complete successfully.

We're backing up to a Digital Ocean Spaces account (which is S3 compatible). 

Sometimes, however, when a backup is run, we get an exception with a `503 Slow Down` response. The package notifies us via Slack that the backup failed, but the deployment script still runs through to completion.

So, in this situation, the CLI commands are still returning an incorrect exit code.

**Comment by mdavis1982** [comment]
In case it's useful, here is the Exception we get and the Exception trace:

### Exception message
```
Error executing "HeadObject" on "https://redacted.ams3.digitaloceanspaces.com/Backups/Redacted/redacted-backup-2018-01-24-02-00-01.zip"; AWS HTTP error: Server error: `HEAD https://redacted.ams3.digitaloceanspaces.com/Backups/Redacted/redacted-backup-2018-01-24-02-00-01.zip` resulted in a `503 Slow Down` response  (server): 503 Slow Down -
```

### Exception trace
```
#0 /home/forge/redacted.com/releases/20180131105054/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php(100): Aws\WrappedHttpHandler->parseError(Array, Object(GuzzleHttp\Psr7\Request), Object(Aws\Command), Array)
#1 /home/forge/redacted.com/releases/20180131105054/vendor/guzzlehttp/promises/src/Promise.php(203): Aws\WrappedHttpHandler->Aws\{closure}(Array)
#2 /home/forge/redacted.com/releases/20180131105054/vendor/guzzlehttp/promises/src/Promise.php(174): GuzzleHttp\Promise\Promise::callHandler(2, Array, Array)
#3 /home/forge/redacted.com/releases/20180131105054/vendor/guzzlehttp/promises/src/RejectedPromise.php(40): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}(Array)
#4 /home/forge/redacted.com/releases/20180131105054/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\RejectedPromise::GuzzleHttp\Promise\{closure}()
#5 /home/forge/redacted.com/releases/20180131105054/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(96): GuzzleHttp\Promise\TaskQueue->run()
#6 /home/forge/redacted.com/releases/20180131105054/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(123): GuzzleHttp\Handler\CurlMultiHandler->tick()
#7 /home/forge/redacted.com/releases/20180131105054/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Handler\CurlMultiHandler->execute(true)
#8 /home/forge/redacted.com/releases/20180131105054/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#9 /home/forge/redacted.com/releases/20180131105054/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#10 /home/forge/redacted.com/releases/20180131105054/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#11 /home/forge/redacted.com/releases/20180131105054/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#12 /home/forge/redacted.com/releases/20180131105054/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#13 /home/forge/redacted.com/releases/20180131105054/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#14 /home/forge/redacted.com/releases/20180131105054/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(58): GuzzleHttp\Promise\Promise->wait()
#15 /home/forge/redacted.com/releases/20180131105054/vendor/aws/aws-sdk-php/src/S3/S3ClientTrait.php(286): Aws\AwsClient->execute(Object(Aws\Command))
#16 /home/forge/redacted.com/releases/20180131105054/vendor/aws/aws-sdk-php/src/S3/S3ClientTrait.php(271): Aws\S3\S3Client->checkExistenceWithCommand(Object(Aws\Command))
#17 /home/forge/redacted.com/releases/20180131105054/vendor/league/flysystem-aws-s3-v3/src/AwsS3Adapter.php(222): Aws\S3\S3Client->doesObjectExist('redacted', 'Backups/Redacted/o...', Array)
#18 /home/forge/redacted.com/releases/20180131105054/vendor/league/flysystem/src/Filesystem.php(57): League\Flysystem\AwsS3v3\AwsS3Adapter->has('Redacted/redacted-bac...')
#19 /home/forge/redacted.com/releases/20180131105054/vendor/league/flysystem/src/Filesystem.php(385): League\Flysystem\Filesystem->has('Redacted/redacted-bac...')
#20 /home/forge/redacted.com/releases/20180131105054/vendor/league/flysystem/src/Filesystem.php(297): League\Flysystem\Filesystem->assertPresent('Redacted/redacted-bac...')
#21 /home/forge/redacted.com/releases/20180131105054/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(363): League\Flysystem\Filesystem->getTimestamp('Redacted/redacted-bac...')
#22 /home/forge/redacted.com/releases/20180131105054/vendor/spatie/laravel-backup/src/BackupDestination/Backup.php(34): Illuminate\Filesystem\FilesystemAdapter->lastModified('Redacted/redacted-bac...')
#23 /home/forge/redacted.com/releases/20180131105054/vendor/spatie/laravel-backup/src/BackupDestination/BackupCollection.php(28): Spatie\Backup\BackupDestination\Backup->date()
#24 /home/forge/redacted.com/releases/20180131105054/vendor/laravel/framework/src/Illuminate/Support/Collection.php(1400): Spatie\Backup\BackupDestination\BackupCollection::Spatie\Backup\BackupDestination\{closure}(Object(Spatie\Backup\BackupDestination\Backup), 13)
#25 /home/forge/redacted.com/releases/20180131105054/vendor/laravel/framework/src/Illuminate/Support/Collection.php(1425): Illuminate\Support\Collection->sortBy(Object(Closure), 0, true)
#26 /home/forge/redacted.com/releases/20180131105054/vendor/spatie/laravel-backup/src/BackupDestination/BackupCollection.php(29): Illuminate\Support\Collection->sortByDesc(Object(Closure))
#27 /home/forge/redacted.com/releases/20180131105054/vendor/spatie/laravel-backup/src/BackupDestination/BackupDestination.php(107): Spatie\Backup\BackupDestination\BackupCollection::createFromFiles(Object(Illuminate\Filesystem\FilesystemAdapter), Array)
#28 /home/forge/redacted.com/releases/20180131105054/vendor/spatie/laravel-backup/src/BackupDestination/BackupDestination.php(143): Spatie\Backup\BackupDestination\BackupDestination->backups()
#29 /home/forge/redacted.com/releases/20180131105054/vendor/spatie/laravel-backup/src/Notifications/BaseNotification.php(46): Spatie\Backup\BackupDestination\BackupDestination->newestBackup()
#30 /home/forge/redacted.com/releases/20180131105054/vendor/spatie/laravel-backup/src/Notifications/Notifications/BackupWasSuccessful.php(36): Spatie\Backup\Notifications\BaseNotification->backupDestinationProperties()
#31 /home/forge/redacted.com/releases/20180131105054/vendor/laravel/framework/src/Illuminate/Notifications/Messages/SlackMessage.php(189): Spatie\Backup\Notifications\Notifications\BackupWasSuccessful->Spatie\Backup\Notifications\Notifications\{closure}(Object(Illuminate\Notifications\Messages\SlackAttachment))
#32 /home/forge/redacted.com/releases/20180131105054/vendor/spatie/laravel-backup/src/Notifications/Notifications/BackupWasSuccessful.php(37): Illuminate\Notifications\Messages\SlackMessage->attachment(Object(Closure))
#33 /home/forge/redacted.com/releases/20180131105054/vendor/laravel/framework/src/Illuminate/Notifications/Channels/SlackWebhookChannel.php(45): Spatie\Backup\Notifications\Notifications\BackupWasSuccessful->toSlack(Object(Spatie\Backup\Notifications\Notifiable))
#34 /home/forge/redacted.com/releases/20180131105054/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(113): Illuminate\Notifications\Channels\SlackWebhookChannel->send(Object(Spatie\Backup\Notifications\Notifiable), Object(Spatie\Backup\Notifications\Notifications\BackupWasSuccessful))
#35 /home/forge/redacted.com/releases/20180131105054/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(89): Illuminate\Notifications\NotificationSender->sendToNotifiable(Object(Spatie\Backup\Notifications\Notifiable), '8d2059b1-c3f6-4...', Object(Spatie\Backup\Notifications\Notifications\BackupWasSuccessful), 'slack')
#36 /home/forge/redacted.com/releases/20180131105054/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(64): Illuminate\Notifications\NotificationSender->sendNow(Array, Object(Spatie\Backup\Notifications\Notifications\BackupWasSuccessful))
#37 /home/forge/redacted.com/releases/20180131105054/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(35): Illuminate\Notifications\NotificationSender->send(Array, Object(Spatie\Backup\Notifications\Notifications\BackupWasSuccessful))
#38 /home/forge/redacted.com/releases/20180131105054/vendor/laravel/framework/src/Illuminate/Notifications/RoutesNotifications.php(18): Illuminate\Notifications\ChannelManager->send(Object(Spatie\Backup\Notifications\Notifiable), Object(Spatie\Backup\Notifications\Notifications\BackupWasSuccessful))
```

**Comment by gerciljunio** [comment]
I had the same problem, I contacted them, and they answered the following:

> Spaces currently supports about 250 requests per second. If you exceed this, you will receive the 503 slow down error you mention. AWS's S3 has much higher rate limits – but it's also a more expensive service.
> 
> Based on what we've seen, you're performing one request for every object in your bucket, which will quickly ramp up to more than 250 requests in a second, and will cause you to receive the 503s. 
> 
> With this level of usage, we generally recommend putting your Spaces behind a CDN or cache, which will allow you to serve files from the Space without ramping up your rate limit. If you're uploading objects to the space, we recommend throttling your rate so you do not exceed the rate limit.

**Comment by freekmurze** [comment]
I'm thinking this problem should be solved in the FlySystem driver. Either by providing some kind of throttling functionality in the S3 driver or a dedicated Spaces driver that has the right throttling baked in.

**Comment by mdavis1982** [comment]
I think this is a different problem to the one I'm reporting.

The Flysystem driver seems like it's properly reporting the error and throwing an exception - fixing that so it doesn't throw the exception is separate to this issue. Having said that, surely this package only attempts to send a single file anyway - the zipped archive - so I don't see how that could hit the rate limit?

The issue here is that, even though the package knows there's been an unsuccessful backup - it gives the unsuccessful notification in Slack - my Envoyer deployment process continues, rather than exiting - suggesting that the package is returning the wrong code at that point.

**Comment by mdavis1982** [comment]
Are there any updates on this yet? 😄

**Comment by freekmurze** [comment]
If you need this fixed fast, feel free to send a PR.

**Comment by leeuwd** [comment]
+1

```
Error executing "HeadObject" on "[URL]"; 
AWS HTTP error: Server error: `HEAD [URL]` 
resulted in a `503 Slow Down` response (server): 503 Slow Down
```

Please see our public Sentry issue: https://sentry.io/share/issue/cdf5fb39945b4a779bc07e903153591c/

**Comment by pehbehbeh** [comment]
Did anybody here come up with a solution yet?

> Having said that, surely this package only attempts to send a single file anyway - the zipped archive - so I don't see how that could hit the rate limit?

@mdavis1982 We are getting this error when executing the cleanup command. https://github.com/spatie/laravel-backup/issues/783#issuecomment-513186709

I would love to contribute via PR but I am not quite sure, where to implement that kind of throttling. My guess is, that [`allFiles` ](https://github.com/spatie/laravel-backup/blob/cc37760ba75e9e07433b6314f37f438a91f7dea4/src/BackupDestination/BackupDestination.php#L107) causes too much requests on DO Spaces, but I need to dig deeper here...

**Comment by mdavis1982** [comment]
@pehbehbeh We didn't ever get this resolved, and, unfortunately when this happens, the deployment doesn't fail and instead carries on.

**Comment by jasperf** [comment]
I would love to contribute via PR but I am not quite sure, where to implement that kind of throttling. My guess is, that allFiles causes too much requests on DO Spaces, but I need to dig deeper here...



> I would love to contribute via PR but I am not quite sure, where to implement that kind of throttling. My guess is, that [`allFiles` ](https://github.com/spatie/laravel-backup/blob/cc37760ba75e9e07433b6314f37f438a91f7dea4/src/BackupDestination/BackupDestination.php#L107) causes too many requests on DO Spaces, but I need to dig deeper here...

We added a comment to @pehbehbeh 's thread https://github.com/spatie/laravel-backup/issues/783#issuecomment-513186709 as we had the exact same issue. Did check https://github.com/spatie/laravel-backup/blob/cc37760ba75e9e07433b6314f37f438a91f7dea4/src/BackupDestination/BackupDestination.php#L107 but not sure right away why @pehbehbeh thought that may be the cause of too many requests. We will look into it too.
