### ISSUE TITLE
Sometimes Backup to Digital Ocean spaces fails

### ISSUE THREAD

**Issue by vmosoti** [spatie/laravel-backup#623]
I have seen the following type of errors being generated for the DO space disk; what could be really causing them, not sure if it's timeouts ...
Server: Ubuntu 16.04
laravel-backup - version 5.1
```
Exception message
An exception occurred while uploading parts to a multipart upload. The following parts had errors:
- Part 4: Error executing "UploadPart" on "https://bucket-name.nyc3.digitaloceanspaces.com/Backup-Name/2018-02-08-04-00-02.zip?partNumber=4&uploadId=2~0dlJLxyGrUes9pFjPIDAHLsN7S83lEy"; AWS HTTP error: cURL error 55: SSL_write() returned SYSCALL, errno = 32 (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)  (server): 100 CONTINUE - 
- Part 2: Error executing "UploadPart" on "https://bucket-name.nyc3.digitaloceanspaces.com/Backup-Name/2018-02-08-04-00-02.zip?partNumber=2&uploadId=2~0dlJLxyGrUes9pFjPIDAHLsN7S83lEy"; AWS HTTP error: cURL error 52: Empty reply from server (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
Exception trace
#0 [internal function]: Aws\Multipart\AbstractUploadManager->Aws\Multipart\{closure}()
#1 /var/www/project/vendor/guzzlehttp/promises/src/Coroutine.php(122): Generator->send(NULL)
#2 /var/www/project/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Promise\Coroutine->_handleSuccess(NULL)
#3 /var/www/project/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, NULL, Array)
#4 /var/www/project/vendor/guzzlehttp/promises/src/TaskQueue.php(47):
```

**Comment by freekmurze** [comment]
This issue belongs more on the repo of the Flysystem driver you are using.
