### ISSUE TITLE
Error running the database backup in another location.

### ISSUE THREAD

**Issue by pedrosalpr** [spatie/laravel-backup#639]
I have two databases, one in development (Homestead Laravel) and one in production. The databases are the same. And I'm using my development environment to back up only the database.

Locally executes the statement with the environment variables of the local database and backs up successfully. 

```bash
php artisan backup:run --only-db
Starting backup...
Dumping database api_logs...
Gzipping api_logs...
Determining files to backup...
Zipping 1 files...
Created zip containing 1 files. Size is 4.98 MB
Copying zip to disk named local...
Successfully copied zip to disk named local.
Backup completed!
```

But if I change the environment variables from the database to the production environment, running locally it gives the error. Remembering that if I test the application with production database, it does queries normally, it runs normally.

```bash
php artisan backup:run --only-db
Starting backup...
Dumping database api_logs...
Backup failed because The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Got error: 1049: Unknown database 'api_logs' when selecting the database
.
#0 /home/vagrant/Projetos/Gitlab/api-arquitetura/vendor/spatie/db-dumper/src/DbDumper.php(222): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully(Object(Symfony\Component\Process\Process))
#1 /home/vagrant/Projetos/Gitlab/api-arquitetura/vendor/spatie/db-dumper/src/Databases/MySql.php(129): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul(Object(Symfony\Component\Process\Process), '/home/vagrant/P...')
#2 /home/vagrant/Projetos/Gitlab/api-arquitetura/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(233): Spatie\DbDumper\Databases\MySql->dumpToFile('/home/vagrant/P...')
#3 [internal function]: Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup\{closure}(Object(Spatie\DbDumper\Databases\MySql), 'mysql')
#4 /home/vagrant/Projetos/Gitlab/api-arquitetura/vendor/laravel/framework/src/Illuminate/Support/Collection.php(861): array_map(Object(Closure), Array, Array)
#5 /home/vagrant/Projetos/Gitlab/api-arquitetura/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(244): Illuminate\Support\Collection->map(Object(Closure))
#6 /home/vagrant/Projetos/Gitlab/api-arquitetura/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(163): Spatie\Backup\Tasks\Backup\BackupJob->dumpDatabases()
#7 /home/vagrant/Projetos/Gitlab/api-arquitetura/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(139): Spatie\Backup\Tasks\Backup\BackupJob->createBackupManifest()
#8 /home/vagrant/Projetos/Gitlab/api-arquitetura/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(52): Spatie\Backup\Tasks\Backup\BackupJob->run()
#9 [internal function]: Spatie\Backup\Commands\BackupCommand->handle()
#10 /home/vagrant/Projetos/Gitlab/api-arquitetura/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#11 /home/vagrant/Projetos/Gitlab/api-arquitetura/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#12 /home/vagrant/Projetos/Gitlab/api-arquitetura/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#13 /home/vagrant/Projetos/Gitlab/api-arquitetura/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#14 /home/vagrant/Projetos/Gitlab/api-arquitetura/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#15 /home/vagrant/Projetos/Gitlab/api-arquitetura/vendor/symfony/console/Command/Command.php(252): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#16 /home/vagrant/Projetos/Gitlab/api-arquitetura/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#17 /home/vagrant/Projetos/Gitlab/api-arquitetura/vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(22): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /home/vagrant/Projetos/Gitlab/api-arquitetura/vendor/symfony/console/Application.php(946): Spatie\Backup\Commands\BaseCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /home/vagrant/Projetos/Gitlab/api-arquitetura/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Spatie\Backup\Commands\BackupCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /home/vagrant/Projetos/Gitlab/api-arquitetura/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /home/vagrant/Projetos/Gitlab/api-arquitetura/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /home/vagrant/Projetos/Gitlab/api-arquitetura/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /home/vagrant/Projetos/Gitlab/api-arquitetura/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 {main}
Backup failed because: The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Got error: 1049: Unknown database 'api_logs' when selecting the database
.

```

And if I run by command line the mysqldump in the production database works correctly.

```bash

mysqldump -h xx.xx.xx.xx -u username -p"password" --databases api_logs --result-file=dump.sql

```

Version
Laravel: 5.5
Laravel-Backup: 5.4

**Comment by freekmurze** [comment]
The error message seems to indicate that there is something wrong with your configuration and not with this package.

**Comment by joseAlex27** [comment]
> The error message seems to indicate that there is something wrong with your configuration and not with this package.

The same answer for everyone......
