### ISSUE TITLE
Version 4! error on creating backup with big project

### ISSUE THREAD

**Issue by Jossnaz** [spatie/laravel-backup#696]
hello

our project has a zipped size of around 1 GB, mainly because there is a big amount of images

notice, I run the code via cronjob like this
```

    protected function schedule(Schedule $schedule)
    {

      $schedule->command('backup:clean')->daily()->at('01:00');
      $schedule->command('backup:run')->daily()->at('02:00');
    }
```

when running the backup last time we got this:

```
Whoops!
Important: An error occurred while backing up mydomain

Exception message: ZipArchive::close(): Read error: No such file or directory


Exception trace: #0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'ZipArchive::clo...', '/var/www/html/w...', 82, Array) #1 /var/www/html/www.mydomain.com/vendor/spatie/laravel-backup/src/Tasks/Backup/Zip.php(82): ZipArchive->close() #2 /var/www/html/www.mydomain.com/vendor/spatie/laravel-backup/src/Tasks/Backup/Zip.php(29): Spatie\Backup\Tasks\Backup\Zip->close() #3 /var/www/html/www.mydomain.com/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(191): Spatie\Backup\Tasks\Backup\Zip::createForManifest(Object(Spatie\Backup\Tasks\Backup\Manifest), '/var/www/html/w...') #4 /var/www/html/www.mydomain.com/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(135): Spatie\Backup\Tasks\Backup\BackupJob->createZipContainingEveryFileInManifest(Object(Spatie\Backup\Tasks\Backup\Manifest)) #5 /var/www/html/www.mydomain.com/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(49): Spatie\Backup\Tasks\Backup\BackupJob->run() #6 [internal function]: Spatie\Backup\Commands\BackupCommand->handle() #7 /var/www/html/www.mydomain.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(508): call_user_func_array(Array, Array) #8 /var/www/html/www.mydomain.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array) #9 /var/www/html/www.mydomain.com/vendor/symfony/console/Command/Command.php(261): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #10 /var/www/html/www.mydomain.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), 

```

**Comment by freekmurze** [comment]
Could you upgrade to v5 and see if the problem is fixed there?

I've seen this package create zip files that are much larger than that, so size isn't the problem. 

Do you have enough disk space free?

**Comment by Jossnaz** [comment]
i fear upgrading to v5 would mean upgrade laravel as well and that isnt an
option in that project

there should be enough disk space

but its been a while since I saw that error actually, i think we can close
it
