### ISSUE TITLE
Lost DB driver

### ISSUE THREAD

**Issue by feralheart** [spatie/laravel-backup#713]
I tried to run the console command but I got this error:

`Backup failed because: Cannot create a dumper for db driver ``. Use `mysql`, `pgsql`, `mongodb` or `sqlite`..`

Stack trace:
```
Exception trace: #0 /var/www/botond/vendor/spatie/laravel-backup/src/Tasks/Backup/DbDumperFactory.php(66): Spatie\Backup\Exceptions\CannotCreateDbDumper::unsupportedDriver('') #1 /var/www/botond/vendor/spatie/laravel-backup/src/Tasks/Backup/DbDumperFactory.php(25): Spatie\Backup\Tasks\Backup\DbDumperFactory::forDriver(NULL) 
#2 /var/www/botond/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJobFactory.php(28): Spatie\Backup\Tasks\Backup\DbDumperFactory::createFromConnection('mysql') 
#3 /var/www/botond/vendor/laravel/framework/src/Illuminate/Support/Collection.php(928): Spatie\Backup\Tasks\Backup\BackupJobFactory::Spatie\Backup\Tasks\Backup{closure}('mysql', 0) 
#4 /var/www/botond/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJobFactory.php(29): Illuminate\Support\Collection->mapWithKeys(Object(Closure)) 
#5 /var/www/botond/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJobFactory.php(14): Spatie\Backup\Tasks\Backup\BackupJobFactory::createDbDumpers(Array) 
#6 /var/www/botond/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(27): Spatie\Backup\Tasks\Backup\BackupJobFactory::createFromArray(Array) 
#7 [internal function]: Spatie\Backup\Commands\BackupCommand->handle() 
#8 /var/www/botond/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array) #9 /var/www/botond/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container{closure}() #10 /var/www/botond/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure)) 
#11 /var/www/botond/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL) 
#12 /var/www/botond/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array) 
#13 /var/www/botond/vendor/symfony/console/Command/Command.php(251): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle)) 
#14 /var/www/botond/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle)) 
#15 /var/www/botond/vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(16): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#16 /var/www/botond/vendor/symfony/console/Application.php(946): Spatie\Backup\Commands\BaseCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#17 /var/www/botond/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Spatie\Backup\Commands\BackupCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#18 /var/www/botond/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#19 /var/www/botond/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#20 /var/www/botond/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#21 /var/www/botond/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#22 {main}
```

I see from that between these parts somewhy it forgets the driver:

```
#1 /var/www/botond/vendor/spatie/laravel-backup/src/Tasks/Backup/DbDumperFactory.php(25): Spatie\Backup\Tasks\Backup\DbDumperFactory::forDriver(NULL) 
#2 /var/www/botond/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJobFactory.php(28): Spatie\Backup\Tasks\Backup\DbDumperFactory::createFromConnection('mysql') 
```

**Comment by freekmurze** [comment]
Make sure this config key contains a valid connection name to your database: https://github.com/spatie/laravel-backup/blob/a5910d990e265d4783831a30ceab2e72d7c27324/config/backup.php#L60

If you changed your config recently, try running `php artisan cache:clear`
