### ISSUE TITLE
backup issue

### ISSUE THREAD

**Issue by netstreet** [spatie/laravel-backup#732]
I have isseue backup files.

Laravel: 5.6
PHP: 7.1

Starting backup...
Dumping database lupus...
Determining files to backup...
Zipping 4732 files...
Created zip containing 4732 files. Size is 109.54 MB
Copying zip to disk named backup...
Successfully copied zip to disk named backup.
Copying zip failed because: Target [Illuminate\Contracts\Notifications\Dispatcher] is not instantiable..
Backup failed because Target [Illuminate\Contracts\Notifications\Dispatcher] is not instantiable..
#0 /Users/jouniikaheimo/Documents/koodit/lupus/vendor/laravel/framework/src/Illuminate/Container/Container.php(773): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /Users/jouniikaheimo/Documents/koodit/lupus/vendor/laravel/framework/src/Illuminate/Container/Container.php(646): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /Users/jouniikaheimo/Documents/koodit/lupus/vendor/laravel/framework/src/Illuminate/Container/Container.php(601): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array)
#3 /Users/jouniikaheimo/Documents/koodit/lupus/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#4 /Users/jouniikaheimo/Documents/koodit/lupus/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): Illuminate\Foundation\Application->make('Illuminate\\Cont...', Array)
#5 /Users/jouniikaheimo/Documents/koodit/lupus/vendor/laravel/framework/src/Illuminate/Notifications/RoutesNotifications.php(18): app('Illuminate\\Cont...')
#6 /Users/jouniikaheimo/Documents/koodit/lupus/vendor/spatie/laravel-backup/src/Notifications/EventHandler.php(33): Spatie\Backup\Notifications\Notifiable->notify(Object(Spatie\Backup\Notifications\Notifications\BackupHasFailed))
#7 /Users/jouniikaheimo/Documents/koodit/lupus/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(360): Spatie\Backup\Notifications\EventHandler->Spatie\Backup\Notifications\{closure}(Object(Spatie\Backup\Events\BackupHasFailed))

**Comment by rafwell** [comment]
Hello. Here I've faced same issue. I've recently upgraded my project from laravel 5.2 to 5.5 and the notification provider was not present in config/app.php.

Make sure the Notifications service provider and facade are registered in app.php:

```
'providers' => [
    // others
    Illuminate\Notifications\NotificationServiceProvider::class,
],
'aliases' => [
    // others
    'Notification' => Illuminate\Support\Facades\Notification::class,
],
```
