### ISSUE TITLE
spatie v5 Backup failed because: ftp_close(): SSL write failed.

### ISSUE THREAD

**Issue by Jossnaz** [spatie/laravel-backup#741]
I've written an issue for v4

I was asked to upgrade to v5

which I did, and I seem to get the same error (a bit more verbose this time)
ftp connection is this

filesystem.php
```
        'ftp' => [
            'driver'   => 'ftp',
            'host' => '123.123.123.123', //as dummy 
            'username' => env('FTPS_USER'),
            'password' => env('FTPS_PW'),
            'root' => 'my_backups',
            'ssl'      => true,
          // Optional FTP Settings...
           'port'     => 21,
        ],
```

```

myuser@osboxes:~/IdeaProjects/myproject/laravel_folder$ art backup:run
Starting backup...
Dumping database laravel_folder...
Determining files to backup...
Zipping 966 files...
Created zip containing 966 files. Size is 97.69 MB
Copying zip to disk named local...
Successfully copied zip to disk named local.
Copying zip to disk named ftp...
Copying zip failed because: ftp_fput(): Accepted data connection.
Backup failed because ftp_close(): SSL write failed.
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'ftp_close(): SS...', '/home/myuser/I...', 229, Array)
#1 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/league/flysystem/src/Adapter/Ftp.php(229): ftp_close(Resource id #3708)
#2 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/league/flysystem/src/Adapter/AbstractFtpAdapter.php(577): League\Flysystem\Adapter\Ftp->disconnect()
#3 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/league/flysystem/src/Adapter/Ftp.php(561): League\Flysystem\Adapter\AbstractFtpAdapter->getConnection()
#4 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/league/flysystem/src/Adapter/Ftp.php(498): League\Flysystem\Adapter\Ftp->ftpRawlist('-alnR', 'MyApp')
#5 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/league/flysystem/src/Adapter/AbstractFtpAdapter.php(322): League\Flysystem\Adapter\Ftp->listDirectoryContents('MyApp', true)
#6 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/league/flysystem/src/Filesystem.php(271): League\Flysystem\Adapter\AbstractFtpAdapter->listContents('MyApp', true)
#7 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(544): League\Flysystem\Filesystem->listContents('MyApp', true)
#8 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(557): Illuminate\Filesystem\FilesystemAdapter->files('MyApp', true)
#9 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/spatie/laravel-backup/src/BackupDestination/BackupDestination.php(103): Illuminate\Filesystem\FilesystemAdapter->allFiles('MyApp')
#10 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/spatie/laravel-backup/src/BackupDestination/BackupDestination.php(140): Spatie\Backup\BackupDestination\BackupDestination->backups()
#11 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/spatie/laravel-backup/src/Notifications/BaseNotification.php(42): Spatie\Backup\BackupDestination\BackupDestination->newestBackup()
#12 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/spatie/laravel-backup/src/Notifications/Notifications/BackupHasFailed.php(25): Spatie\Backup\Notifications\BaseNotification->backupDestinationProperties()
#13 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(50): Spatie\Backup\Notifications\Notifications\BackupHasFailed->toMail(Object(Spatie\Backup\Notifications\Notifiable))
#14 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(113): Illuminate\Notifications\Channels\MailChannel->send(Object(Spatie\Backup\Notifications\Notifiable), Object(Spatie\Backup\Notifications\Notifications\BackupHasFailed))
#15 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(89): Illuminate\Notifications\NotificationSender->sendToNotifiable(Object(Spatie\Backup\Notifications\Notifiable), 'dfe2d78d-c60b-4...', Object(Spatie\Backup\Notifications\Notifications\BackupHasFailed), 'mail')
#16 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(64): Illuminate\Notifications\NotificationSender->sendNow(Array, Object(Spatie\Backup\Notifications\Notifications\BackupHasFailed))
#17 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(35): Illuminate\Notifications\NotificationSender->send(Array, Object(Spatie\Backup\Notifications\Notifications\BackupHasFailed))
#18 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/laravel/framework/src/Illuminate/Notifications/RoutesNotifications.php(18): Illuminate\Notifications\ChannelManager->send(Object(Spatie\Backup\Notifications\Notifiable), Object(Spatie\Backup\Notifications\Notifications\BackupHasFailed))
#19 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/spatie/laravel-backup/src/Notifications/EventHandler.php(33): Spatie\Backup\Notifications\Notifiable->notify(Object(Spatie\Backup\Notifications\Notifications\BackupHasFailed))
#20 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(350): Spatie\Backup\Notifications\EventHandler->Spatie\Backup\Notifications\{closure}(Object(Spatie\Backup\Events\BackupHasFailed))
#21 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(200): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('Spatie\\Backup\\E...', Array)
#22 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(465): Illuminate\Events\Dispatcher->dispatch('Spatie\\Backup\\E...')
#23 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(268): event(Object(Spatie\Backup\Events\BackupHasFailed))
#24 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(260): Spatie\Backup\Tasks\Backup\BackupJob->sendNotification(Object(Spatie\Backup\Events\BackupHasFailed))
#25 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/laravel/framework/src/Illuminate/Support/Collection.php(339): Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup\{closure}(Object(Spatie\Backup\BackupDestination\BackupDestination), 1)
#26 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(262): Illuminate\Support\Collection->each(Object(Closure))
#27 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(149): Spatie\Backup\Tasks\Backup\BackupJob->copyToBackupDestinations('/home/myuser/I...')
#28 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(52): Spatie\Backup\Tasks\Backup\BackupJob->run()
#29 [internal function]: Spatie\Backup\Commands\BackupCommand->handle()
#30 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#31 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#32 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#33 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#34 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#35 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/symfony/console/Command/Command.php(251): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#36 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#37 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(16): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#38 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/symfony/console/Application.php(946): Spatie\Backup\Commands\BaseCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#39 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Spatie\Backup\Commands\BackupCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#40 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#41 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#42 /home/myuser/IdeaProjects/myproject/laravel_folder/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#43 /home/myuser/IdeaProjects/myproject/laravel_folder/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#44 {main}
Backup failed because: ftp_close(): SSL write failed.
```

**Comment by freekmurze** [comment]
I'm thinking this is not an issue of Laravel backup, but of the latests version of the FlySystem ftp driver. All ftp work is handler to that driver. Open up an issue there.

Try to prepare a little example for them that shows copying your zip does not work.

If you believe the error originates in our package, please open up a failing PR for us to look at.
