### ISSUE TITLE
Backup clean fails - file not found

### ISSUE THREAD

**Issue by chrisGeonet** [spatie/laravel-backup#746]
Running backup:clean for the following config will result in an error
Cleanup failed because: File not found at path: backups/site_2017-08-21-16-07-13.zip

Exactly like issue #505 

I am still getting this problem using 5.10.1.
I have two backups 2.6gb in size, and have deleteOldestBackupsWhenUsingMoreMegabytesThan set to 5000.
When i run a cleanup it deletes the oldest backup, then errors saying the same file cannot be found

**Comment by Jaspur** [comment]
Still happening here too 
```
Whoops!

An error occurred while cleaning up the backups of Mijn Bewijsstukken

Exception message: File not found at path: backups-ws/2018-08-31-02-00-03.zip

Exception trace: #0 /home/forge/the.website.nl/vendor/league/flysystem/src/Filesystem.php(297): League\Flysystem\Filesystem->assertPresent('backups-ws/201...') #1 /home/forge/the.website.nl/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(363): League\Flysystem\Filesystem->getTimestamp('backups-ws/201...') #2 /home/forge/the.website.nl/vendor/spatie/laravel-backup/src/BackupDestination/Backup.php(35): Illuminate\Filesystem\FilesystemAdapter->lastModified('backups-ws/201...') #3 /home/forge/the.website.nl/vendor/spatie/laravel-backup/src/Notifications/BaseNotification.php(52): Spatie\Backup\BackupDestination\Backup->date() #4 /home/forge/the.website.nl/vendor/spatie/laravel-backup/src/Notifications/Notifications/CleanupWasSuccessful.php(22): Spatie\Backup\Notifications\BaseNotification->backupDestinationProperties() #5 /home/forge/the.website.nl/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(50): Spatie\Backup\Notifications\Notifications\CleanupWasSuccessful->toMail(Object(Spatie\Backup\Notifications\Notifiable)) #6 /home/forge/the.website.nl/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(113): Illuminate\Notifications\Channels\MailChannel->send(Object(Spatie\Backup\Notifications\Notifiable), Object(Spatie\Backup\Notifications\Notifications\CleanupWasSuccessful)) #7 /home/forge/the.website.nl/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(89): Illuminate\Notifications\NotificationSender->sendToNotifiable(Object(Spatie\Backup\Notifications\Notifiable), '6baae521-bcc8-4...', Object(Spatie\Backup\Notifications\Notifications\CleanupWasSuccessful), 'mail') #8 /home/forge/the.website.nl/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(64): Illuminate\Notifications\NotificationSender->sendNow(Array, Object(Spatie\Backup\Notifications\Notifications\CleanupWasSuccessful)) #9 /home/forge/the.website.nl/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(35): Illuminate\Notifications\NotificationSender->send(Array, Object(Spatie\Backup\Notifications\Notifications\CleanupWasSuccessful)) #10 /home/forge/the.website.nl/vendor/laravel/framework/src/Illuminate/Notifications/RoutesNotifications.php(18): Illuminate\Notifications\ChannelManager->send(Object(Spatie\Backup\Notifications\Notifiable), Object(Spatie\Backup\Notifications\Notifications\CleanupWasSuccessful)) #11 /home/forge/the.website.nl/vendor/spatie/laravel-backup/src/Notifications/EventHandler.php(33): Spatie\Backup\Notifications\Notifiable->notify(Object(Spatie\Backup\Notifications\Notifications\CleanupWasSuccessful)) #12 /home/forge/the.website.nl/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(360): Spatie\Backup\Notifications\EventHandler->Spatie\Backup\Notifications{closure}(Object(Spatie\Backup\Events\CleanupWasSuccessful)) #13 /home/forge/the.website.nl/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(209): Illuminate\Events\Dispatcher->Illuminate\Events{closure}('Spatie\Backup\E...', Array) #14 /home/forge/the.website.nl/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(476): Illuminate\Events\Dispatcher->dispatch('Spatie\Backup\E...') #15 /home/forge/the.website.nl/vendor/spatie/laravel-backup/src/Tasks/Cleanup/CleanupJob.php(60): event(Object(Spatie\Backup\Events\CleanupWasSuccessful)) #16 /home/forge/the.website.nl/vendor/spatie/laravel-backup/src/Tasks/Cleanup/CleanupJob.php(43): Spatie\Backup\Tasks\Cleanup\CleanupJob->sendNotification(Object(Spatie\Backup\Events\CleanupWasSuccessful)) #17 /home/forge/the.website.nl/vendor/laravel/framework/src/Illuminate/Support/Collection.php(397): Spatie\Backup\Tasks\Cleanup\CleanupJob->Spatie\Backup\Tasks\Cleanup{closure}(Object(Spatie\Backup\BackupDestination\BackupDestination), 0) #18 /home/forge/the.website.nl/vendor/spatie/laravel-backup/src/Tasks/Cleanup/CleanupJob.php(54): Illuminate\Support\Collection->each(Object(Closure)) #19 /home/forge/the.website.nl/vendor/spatie/laravel-backup/src/Commands/CleanupCommand.php(42): Spatie\Backup\Tasks\Cleanup\CleanupJob->run() #20 [internal function]: Spatie\Backup\Commands\CleanupCommand->handle() #21 /home/forge/the.website.nl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array) #22 /home/forge/the.website.nl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container{closure}() #23 /home/forge/the.website.nl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure)) #24 /home/forge/the.website.nl/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL) #25 /home/forge/the.website.nl/vendor/laravel/framework/src/Illuminate/Console/Command.php(179): Illuminate\Container\Container->call(Array) #26 /home/forge/the.website.nl/vendor/symfony/console/Command/Command.php(251): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle)) #27 /home/forge/the.website.nl/vendor/laravel/framework/src/Illuminate/Console/Command.php(166): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle)) #28 /home/forge/the.website.nl/vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(16): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #29 /home/forge/the.website.nl/vendor/symfony/console/Application.php(886): Spatie\Backup\Commands\BaseCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #30 /home/forge/the.website.nl/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(Spatie\Backup\Commands\CleanupCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #31 /home/forge/the.website.nl/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #32 /home/forge/the.website.nl/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #33 /home/forge/the.website.nl/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #34 /home/forge/the.website.nl/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #35 {main}
```
