### ISSUE TITLE
Object of class Spatie\Backup\Notifications\Notifiable could not be converted to string

### ISSUE THREAD

**Issue by egknight** [spatie/laravel-backup#787]
Hello,

I keep getting the following notification in my slack channel

Object of class Spatie\Backup\Notifications\Notifiable could not be converted to string

I have no idea why, can someone give me a pointer or is it a bug?

Thanks

**Comment by freekmurze** [comment]
The tests prove that this functionality is working as intended. Can you submit a failing test for me to look at?

**Comment by Braunson** [comment]
Also having this issue seemingly since the last release..

**Comment by Braunson** [comment]
So if I disable Laravel Telescope, this issues exception is not thrown or recorded in the `laravel.log` but I do see the error in CLI from the command `php artisan backup:run`.

So it looks like it's a Laravel Telescope issue. Possible fixes are formatting the error from the Backup "plugin", in this case that would be Google but it can also be a fix to the Google Drive package.

**Comment by freekmurze** [comment]
I'm thinking this should be reported and fixed over at Telescope.

**Comment by Braunson** [comment]
@freekmurze That was my issue at least, I'm not sure if @egknight is using Telescope or the Google Drive Package.

**Comment by egknight** [comment]
I am also using telescope @Braunson

**Comment by themsaid** [comment]
Any idea what's the root of this issue in Telescope? I can't replicate it.

**Comment by egknight** [comment]
Does this help...

```
Message
Object of class Spatie\Backup\Notifications\Notifiable could not be converted to string
Level
ERROR
Exception
```{
   "class": "ErrorException",
   "message": "Object of class Spatie\\Backup\\Notifications\\Notifiable could not be converted to string",
   "code": 0,
   "file": "\/home\/forge\/staging-01.domain.co.uk\/vendor\/laravel\/framework\/src\/Illuminate\/Support\/Str.php:338",
   "trace": [
       "{\"function\":\"handleError\",\"class\":\"Illuminate\\\\Foundation\\\\Bootstrap\\\\HandleExceptions\",\"type\":\"->\",\"args\":[4096,\"Object of class Spatie\\\\Backup\\\\Notifications\\\\Notifiable could not be converted to string\",\"\/home\/forge\/staging-01.domain.co.uk\/vendor\/laravel\/framework\/src\/Illuminate\/Support\/Str.php\",338,{\"search\":\"?\",\"replace\":\"[object] (Spatie\\\\Backup\\\\Notifications\\\\Notifiable: {})\",\"subject\":\"insert into `telescope_entries_tags` (`entry_uuid`, `tag`) values (8c6c99d8-a363-4894-925b-633718e3e867, ?)\",\"position\":105}]}",
       "\/home\/forge\/staging-01.domain.co.uk\/vendor\/laravel\/framework\/src\/Illuminate\/Support\/Str.php:338",
       "\/home\/forge\/staging-01.domain.co.uk\/vendor\/laravel\/framework\/src\/Illuminate\/Support\/Str.php:315",
       "\/home\/forge\/staging-01.domain.co.uk\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/QueryException.php:56",
       "\/home\/forge\/staging-01.domain.co.uk\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/QueryException.php:39",
       "\/home\/forge\/staging-01.domain.co.uk\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connection.php:665",
       "\/home\/forge\/staging-01.domain.co.uk\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connection.php:624",
       "\/home\/forge\/staging-01.domain.co.uk\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connection.php:459",
       "\/home\/forge\/staging-01.domain.co.uk\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connection.php:411",
       "\/home\/forge\/staging-01.domain.co.uk\/vendor\/lar…
```

**Comment by Braunson** [comment]
@themsaid Use Laravel Backup + Google Package (to backup to Google) and then for me, it was thrown when I was exceeding the daily limit `dailyLimitExceededUnreg` of API calls presumably.

**Comment by egknight** [comment]
I am backing up to Spaces on Digital Ocean using S3 disk.

From the main log..

```
[2018-12-05 03:30:54] production.ERROR: Object of class Spatie\Backup\Notifications\Notifiable could not be converted to string {"exception":"[object] (ErrorException(code: 0): Object of class Spatie\\Backup\\Notifications\\Notifiable could not be converted to string at /home/forge/staging-01.domain.co.uk/vendor/laravel/framework/src/Illuminate/Support/Str.php:338)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(4096, 'Object of class...', '/home/forge/sta...', 338, Array)
#1 /home/forge/staging-01.domain.co.uk/vendor/laravel/framework/src/Illuminate/Support/Str.php(338): substr_replace('insert into `te...', Object(Spatie\\Backup\\Notifications\\Notifiable), 105, 1)
#2 /home/forge/staging-01.domain.co.uk/vendor/laravel/framework/src/Illuminate/Support/Str.php(315): Illuminate\\Support\\Str::replaceFirst('?', Object(Spatie\\Backup\\Notifications\\Notifiable), 'insert into `te...')
#3 /home/forge/staging-01.domain.co.uk/vendor/laravel/framework/src/Illuminate/Database/QueryException.php(56): Illuminate\\Support\\Str::replaceArray('?', Array, 'insert into `te...')
#4 /home/forge/staging-01.domain.co.uk/vendor/laravel/framework/src/Illuminate/Database/QueryException.php(39): Illuminate\\Database\\QueryException->formatMessage('insert into `te...', Array, Object(ErrorException))
#5 /home/forge/staging-01.domain.co.uk/vendor/laravel/framework/src/Illuminate/Database/Connection.php(665): Illuminate\\Database\\QueryException->__construct('insert into `te...', Array, Object(ErrorException))
#6 /home/forge/staging-01.domain.co.uk/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('insert into `te...', Array, Object(Closure))
#7 /home/forge/staging-01.domain.co.uk/vendor/laravel/framework/src/Illuminate/Database/Connection.php(459): Illuminate\\Database\\Connection->run('insert into `te...', Array, Object(Closure))
#8 /home/forge/staging-01.domain.co.uk/vendor/laravel/framework/src/Illuminate/Database/Connection.php(411): Illuminate\\Database\\Connection->statement('insert into `te...', Array)
#9 /home/forge/staging-01.domain.co.uk/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2578): Illuminate\\Database\\Connection->insert('insert into `te...', Array)
#10 /home/forge/staging-01.domain.co.uk/vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php(166): Illuminate\\Database\\Query\\Builder->insert(Array)
#11 /home/forge/staging-01.domain.co.uk/vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php(118): Laravel\\Telescope\\Storage\\DatabaseEntriesRepository->storeTags(Object(Illuminate\\Support\\Collection))
#12 /home/forge/staging-01.domain.co.uk/vendor/laravel/telescope/src/Telescope.php(484): Laravel\\Telescope\\Storage\\DatabaseEntriesRepository->store(Object(Illuminate\\Support\\Collection))
#13 /home/forge/staging-01.domain.co.uk/vendor/laravel/telescope/src/ListensForStorageOpportunities.php(45): Laravel\\Telescope\\Telescope::store(Object(Laravel\\Telescope\\Storage\\DatabaseEntriesRepository))
#14 [internal function]: Laravel\\Telescope\\Telescope::Laravel\\Telescope\\{closure}()
#15 /home/forge/staging-01.domain.co.uk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Object(Closure), Array)
#16 /home/forge/staging-01.domain.co.uk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(75): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#17 /home/forge/staging-01.domain.co.uk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Object(Closure), Object(Closure))
#18 /home/forge/staging-01.domain.co.uk/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Object(Closure), Array, NULL)
#19 /home/forge/staging-01.domain.co.uk/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(967): Illuminate\\Container\\Container->call(Object(Closure))
#20 /home/forge/staging-01.domain.co.uk/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(149): Illuminate\\Foundation\\Application->terminate()
#21 /home/forge/staging-01.domain.co.uk/artisan(51): Illuminate\\Foundation\\Console\\Kernel->terminate(Object(Symfony\\Component\\Console\\Input\\ArgvInput), 0)
#22 {main}
"}
```

**Comment by sebastiaanluca** [comment]
Just had this issue in production when deploying. Before we do so, we run in `php artisan backup:run` in an Envoyer deployment hook.

The only noteworthy change was an update of the Laravel Framework:

```diff
- "laravel/framework": "~5.7.13",
+ "laravel/framework": "~5.7.15",
```

**Comment by themsaid** [comment]
I think you'll need to inspect what's being recorded, you may dd() or something at the beginning of `DatabaseEntriesRepository::store()` method to see what's being passed.

**Comment by themsaid** [comment]
Ok we've fixed that in https://github.com/laravel/telescope/commit/0287613e09639dd0784de53ca587e665082b7618

**Comment by freekmurze** [comment]
Thanks @themsaid 👍
