### ISSUE TITLE
The process has been signaled with signal "11"

### ISSUE THREAD

**Issue by ChristianBundgaard** [spatie/laravel-backup#946]
Have been using this plugin for a while, and it normally works like a charm. A few days ago I started getting this error. Any suggestions?

Using symfony 4.3.3 (I think) and Laravel 5.8. Full list of packages attached.

```
Backup failed because The process has been signaled with signal "11"..
#0 /home/forge/pashion.dk/vendor/symfony/process/Process.php(235): Symfony\Component\Process\Process->wait()
#1 /home/forge/pashion.dk/vendor/spatie/db-dumper/src/Databases/MySql.php(188): Symfony\Component\Process\Process->run()
#2 /home/forge/pashion.dk/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(250): Spatie\DbDumper\Databases\MySql->dumpToFile('/home/forge/pas...')
#3 [internal function]: Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup\{closure}(Object(Spatie\DbDumper\Databases\MySql), 'mysql')
#4 /home/forge/pashion.dk/vendor/laravel/framework/src/Illuminate/Support/Collection.php(1120): array_map(Object(Closure), Array, Array)
#5 /home/forge/pashion.dk/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(253): Illuminate\Support\Collection->map(Object(Closure))
#6 /home/forge/pashion.dk/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(167): Spatie\Backup\Tasks\Backup\BackupJob->dumpDatabases()
#7 /home/forge/pashion.dk/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(143): Spatie\Backup\Tasks\Backup\BackupJob->createBackupManifest()
#8 /home/forge/pashion.dk/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(52): Spatie\Backup\Tasks\Backup\BackupJob->run()
#9 [internal function]: Spatie\Backup\Commands\BackupCommand->handle()
#10 /home/forge/pashion.dk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#11 /home/forge/pashion.dk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#12 /home/forge/pashion.dk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#13 /home/forge/pashion.dk/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#14 /home/forge/pashion.dk/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#15 /home/forge/pashion.dk/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#16 /home/forge/pashion.dk/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#17 /home/forge/pashion.dk/vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(16): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /home/forge/pashion.dk/vendor/symfony/console/Application.php(921): Spatie\Backup\Commands\BaseCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /home/forge/pashion.dk/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Spatie\Backup\Commands\BackupCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /home/forge/pashion.dk/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /home/forge/pashion.dk/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /home/forge/pashion.dk/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(133): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /home/forge/pashion.dk/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 {main}
Backup failed because: The process has been signaled with signal "11"..
```

PACKAGES
```
activecampaign/api-php                v2.0.3   Official PHP wrapper for the ActiveCampaign API.
artesaos/seotools                     v0.12.2  SEO Tools for Laravel and Lumen
aws/aws-sdk-php                       3.109.6  AWS SDK for PHP - Use Amazon Web Services in your PHP project
barryvdh/laravel-debugbar             v3.2.4   PHP Debugbar integration for Laravel
beyondcode/laravel-dump-server        1.3.0    Symfony Var-Dump Server for Laravel
biscolab/laravel-recaptcha            v3.5.0   Simple ReCaptcha package for Laravel 5
chumper/zipper                        v1.0.2   This is a little neat helper for the ZipArchive methods with handy functions
clue/stream-filter                    v1.4.1   A simple and modern approach to stream filtering in PHP
dnoegel/php-xdg-base-dir              0.1      implementation of xdg base directory specification for php
doctrine/cache                        v1.8.0   Caching library offering an object-oriented API for many cache backends
doctrine/dbal                         v2.9.2   Powerful PHP database abstraction layer (DBAL) with many features for database schema introspe...
doctrine/event-manager                v1.0.0   Doctrine Event Manager component
doctrine/inflector                    v1.3.0   Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator                 1.2.0    A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                        1.1.0    PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
dragonmantank/cron-expression         v2.3.0   CRON for PHP: Calculate the next or previous run date and determine if a CRON expression is due
egulias/email-validator               2.1.11   A library for validating emails against several RFCs
erusev/parsedown                      1.7.3    Parser for Markdown.
fideloper/proxy                       4.2.0    Set trusted proxies for Laravel
filp/whoops                           2.5.0    php error handling for cool kids
fzaninotto/faker                      v1.8.0   Faker is a PHP library that generates fake data for you.
graham-campbell/markdown              v10.3.1  Markdown Is A CommonMark Wrapper For Laravel 5
guzzlehttp/guzzle                     6.3.3    Guzzle is a PHP HTTP client library
guzzlehttp/promises                   v1.3.1   Guzzle promises library
guzzlehttp/psr7                       1.6.1    PSR-7 message implementation that also provides common utility methods
hamcrest/hamcrest-php                 v2.0.0   This is the PHP port of Hamcrest Matchers
http-interop/http-factory-guzzle      1.0.0    An HTTP Factory using Guzzle PSR7
jakub-onderka/php-console-color       v0.2    
jakub-onderka/php-console-highlighter v0.4     Highlight PHP code in terminal
jean85/pretty-package-versions        1.2      A wrapper for ocramius/package-versions to get pretty versions strings
jenssegers/date                       v3.5.0   A date library to help you work with dates in different languages
kalnoy/nestedset                      v4.3.5   Nested Set Model for Laravel 5.7 and up
laravel/framework                     v5.8.32  The Laravel Framework.
laravel/telescope                     v2.0.6   An elegant debug assistant for the Laravel framework.
laravel/tinker                        v1.0.10  Powerful REPL for the Laravel framework.
laravelcollective/html                v5.8.0   HTML and Form Builders for the Laravel Framework
league/commonmark                     0.18.5   PHP Markdown parser based on the CommonMark spec
league/flysystem                      1.0.53   Filesystem abstraction: Many filesystems, one API.
league/flysystem-aws-s3-v3            1.0.23   Flysystem adapter for the AWS S3 SDK v3.x
maatwebsite/excel                     3.1.15   Supercharged Excel exports and imports in Laravel
markbaker/complex                     1.4.7    PHP Class for working with complex numbers
markbaker/matrix                      1.1.4    PHP Class for working with matrices
maximebf/debugbar                     v1.15.0  Debug bar in the browser for php application
mcamara/laravel-localization          1.3.20   Easy localization for Laravel
mockery/mockery                       1.2.3    Mockery is a simple yet flexible PHP mock object framework
monolog/monolog                       1.24.0   Sends your logs to files, sockets, inboxes, databases and various web services
moontoast/math                        1.1.2    A mathematics library, providing functionality for large numbers
mtdowling/jmespath.php                2.4.0    Declaratively specify how to extract elements from a JSON document
myclabs/deep-copy                     1.9.3    Create deep copies (clones) of your objects
nesbot/carbon                         2.23.0   A API extension for DateTime that supports 281 different languages.
nikic/php-parser                      v4.2.3   A PHP parser written in PHP
nunomaduro/collision                  v2.1.1   Cli error handling for console/command-line PHP applications.
ocramius/package-versions             1.5.1    Composer plugin that provides efficient querying for installed package versions (no runtime IO)
opis/closure                          3.3.1    A library that can be used to serialize closures (anonymous functions) and arbitrary objects.
paragonie/random_compat               v9.99.99 PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
phar-io/manifest                      1.0.3    Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                       2.0.1    Library for handling version information and constraints
php-http/client-common                2.0.0    Common HTTP Client implementations and tools for HTTPlug
php-http/curl-client                  2.0.0    PSR-18 and HTTPlug Async client with cURL
php-http/discovery                    1.7.0    Finds installed HTTPlug implementations and PSR-7 message factories
php-http/httplug                      v2.0.0   HTTPlug, the HTTP client abstraction for PHP
php-http/message                      1.8.0    HTTP Message related tools
php-http/message-factory              v1.0.2   Factory interfaces for PSR-7 HTTP Message
php-http/promise                      v1.0.0   Promise used for asynchronous HTTP requests
phpdocumentor/reflection-common       1.0.1    Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock     4.3.1    With this component, a library can provide support for annotations via DocBlocks or otherwise ...
phpdocumentor/type-resolver           0.4.0   
phpoffice/phpspreadsheet              1.8.2    PHPSpreadsheet - Read, Create and Write Spreadsheet documents in PHP - Spreadsheet engine
phpoption/phpoption                   1.5.0    Option Type for PHP
phpspec/prophecy                      1.8.1    Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage             6.1.4    Library that provides collection, processing, and rendering functionality for PHP code coverag...
phpunit/php-file-iterator             2.0.2    FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template             1.2.1    Simple template engine.
phpunit/php-timer                     2.1.2    Utility class for timing
phpunit/php-token-stream              3.1.0    Wrapper around PHP's tokenizer extension.
phpunit/phpunit                       7.5.14   The PHP Unit Testing framework.
predis/predis                         v1.1.1   Flexible and feature-complete Redis client for PHP and HHVM
prewk/xml-string-streamer             0.11.0   Stream large XML files with low memory consumption
psr/container                         1.0.0    Common Container Interface (PHP FIG PSR-11)
psr/http-client                       1.0.0    Common interface for HTTP clients
psr/http-factory                      1.0.1    Common interfaces for PSR-7 HTTP message factories
psr/http-message                      1.0.1    Common interface for HTTP messages
psr/log                               1.1.0    Common interface for logging libraries
psr/simple-cache                      1.0.1    Common interfaces for simple caching
psy/psysh                             v0.9.9   An interactive shell for modern PHP.
ralouphie/getallheaders               3.0.3    A polyfill for getallheaders.
ramsey/uuid                           3.8.0    Formerly rhumsaa/uuid. A PHP 5.4+ library for generating RFC 4122 version 1, 3, 4, and 5 unive...
sebastian/code-unit-reverse-lookup    1.0.1    Looks up which function or method a line of code belongs to
sebastian/comparator                  3.0.2    Provides the functionality to compare PHP values for equality
sebastian/diff                        3.0.2    Diff implementation
sebastian/environment                 4.2.2    Provides functionality to handle HHVM/PHP environments
sebastian/exporter                    3.1.1    Provides the functionality to export PHP variables for visualization
sebastian/global-state                2.0.0    Snapshotting of global state
sebastian/object-enumerator           3.0.3    Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector            1.1.1    Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context           3.0.0    Provides functionality to recursively process PHP variables
sebastian/resource-operations         2.0.1    Provides a list of PHP built-in functions that operate on resources
sebastian/version                     2.0.1    Library that helps with managing the version number of Git-hosted PHP projects
sentry/sdk                            2.0.3    This is a metapackage shipping sentry/sentry with a recommended http client.
sentry/sentry                         2.1.1    A PHP SDK for Sentry (http://sentry.io)
sentry/sentry-laravel                 1.0.1    Laravel SDK for Sentry (https://sentry.io)
shipping-docker/vessel                3.2.0    Simple Docker dev environments
spatie/array-to-xml                   2.11.1   Convert an array to xml
spatie/db-dumper                      2.14.2   Dump databases
spatie/laravel-backup                 6.3.1    A Laravel package to backup your application
spatie/laravel-cookie-consent         2.8.0    Make your Laravel app comply with the crazy EU cookie law
spatie/laravel-permission             2.37.0   Permission handling for Laravel 5.4 and up
spatie/laravel-translation-loader     2.3.0    Store your language lines in the database, yaml or other sources
spatie/schema-org                     2.3.0    A fluent builder Schema.org types and ld+json generator
spatie/temporary-directory            1.2.0    Easily create, use and destroy temporary directories
swiftmailer/swiftmailer               v6.2.1   Swiftmailer, free feature-rich PHP mailer
symfony/console                       v4.3.3   Symfony Console Component
symfony/css-selector                  v4.3.3   Symfony CssSelector Component
symfony/debug                         v4.3.3   Symfony Debug Component
symfony/event-dispatcher              v4.3.3   Symfony EventDispatcher Component
symfony/event-dispatcher-contracts    v1.1.5   Generic abstractions related to dispatching event
symfony/finder                        v4.3.3   Symfony Finder Component
symfony/http-foundation               v4.3.3   Symfony HttpFoundation Component
symfony/http-kernel                   v4.3.3   Symfony HttpKernel Component
symfony/mime                          v4.3.3   A library to manipulate MIME messages
symfony/options-resolver              v4.3.3   Symfony OptionsResolver Component
symfony/polyfill-ctype                v1.12.0  Symfony polyfill for ctype functions
symfony/polyfill-iconv                v1.12.0  Symfony polyfill for the Iconv extension
symfony/polyfill-intl-idn             v1.12.0  Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-mbstring             v1.12.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php72                v1.12.0  Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73                v1.12.0  Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/process                       v4.3.3   Symfony Process Component
symfony/routing                       v4.3.3   Symfony Routing Component
symfony/service-contracts             v1.1.5   Generic abstractions related to writing services
symfony/translation                   v4.3.3   Symfony Translation Component
symfony/translation-contracts         v1.1.5   Generic abstractions related to translation
symfony/var-dumper                    v4.3.3   Symfony mechanism for exploring and dumping PHP variables
theseer/tokenizer                     1.1.3    A small library for converting tokenized PHP source code into XML and potentially other formats
tijsverkoyen/css-to-inline-styles     2.2.1    CssToInlineStyles is a class that enables you to convert HTML-pages/files into HTML-pages/file...
vlucas/phpdotenv                      v3.4.0   Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automagically.
webmozart/assert                      1.4.0    Assertions to validate method input/output with nice error messages.
zendframework/zend-diactoros          2.1.3    PSR HTTP Message implementations
```

**Comment by vdbelt** [comment]
Could you update your dependencies, and verify you are using the newest release of `spatie/db-dumper`?

The newest release (2.14.3) of `spatie/db-dumper` contains a fix for a memory leak, that may be the root cause of your issue. 

Let us know if it works for you.

**Comment by atymic** [comment]
@ChristianBundgaard Did you have any luck with the fix?

**Comment by ChristianBundgaard** [comment]
Hey, sorry for my late response. I ended up downgrading temporarily, even PHP, since I couldn't find a solution. It works now, so I suppose that either PHP or a package fixed a bug somewhere.
